/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoMath {
        /**
          * To set the component has being editable (contenteditable will be applied on the slot on click)
         */
        "editable": boolean;
        /**
          * A collection of custom macros. Each macro is a property with a name like \name (written "\name" in JavaScript) which maps to a string that describes the expansion of the macro, or a function that accepts an instance of MacroExpander as first argument and returns the expansion as a string.
         */
        "macros": string;
    }
}
declare global {
    interface HTMLDeckgoMathElement extends Components.DeckgoMath, HTMLStencilElement {
    }
    var HTMLDeckgoMathElement: {
        prototype: HTMLDeckgoMathElement;
        new (): HTMLDeckgoMathElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-math": HTMLDeckgoMathElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoMath {
        /**
          * To set the component has being editable (contenteditable will be applied on the slot on click)
         */
        "editable"?: boolean;
        /**
          * A collection of custom macros. Each macro is a property with a name like \name (written "\name" in JavaScript) which maps to a string that describes the expansion of the macro, or a function that accepts an instance of MacroExpander as first argument and returns the expansion as a string.
         */
        "macros"?: string;
        /**
          * Emit the host element when modified
         */
        "onMathDidChange"?: (event: CustomEvent<HTMLElement>) => void;
    }
    interface IntrinsicElements {
        "deckgo-math": DeckgoMath;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-math": LocalJSX.DeckgoMath & JSXBase.HTMLAttributes<HTMLDeckgoMathElement>;
        }
    }
}
