/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DeckgoQrcode {
    'content': string;
    'generate': () => Promise<void>;
    'qrAlt': string;
    'qrBackgroundColor': string;
    'qrCellSize': number;
    'qrFillColor': string;
    'qrMargin': number;
    'type': string;
  }
}

declare global {


  interface HTMLDeckgoQrcodeElement extends Components.DeckgoQrcode, HTMLStencilElement {}
  var HTMLDeckgoQrcodeElement: {
    prototype: HTMLDeckgoQrcodeElement;
    new (): HTMLDeckgoQrcodeElement;
  };
  interface HTMLElementTagNameMap {
    'deckgo-qrcode': HTMLDeckgoQrcodeElement;
  }
}

declare namespace LocalJSX {
  interface DeckgoQrcode extends JSXBase.HTMLAttributes<HTMLDeckgoQrcodeElement> {
    'content'?: string;
    'qrAlt'?: string;
    'qrBackgroundColor'?: string;
    'qrCellSize'?: number;
    'qrFillColor'?: string;
    'qrMargin'?: number;
    'type'?: string;
  }

  interface IntrinsicElements {
    'deckgo-qrcode': DeckgoQrcode;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


