name: google-key-updater
license: AGPL-3

executable:
    main: Main.hs

dependencies:
    - aeson
    - base
    - bytestring
    - http-client
    - http-client-tls
    - http-conduit
    - http-types
    - servant
    - servant-client
    - servant-server
    - text
    - wai
    - wai-cors
    - unliftio
    - wai-lambda
    - warp
    - amazonka
    - amazonka-core
    - amazonka-s3
