/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'deckdeckgo-charts';
import 'deckdeckgo-highlight-code';
import 'deckdeckgo-inline-editor';
import 'deckdeckgo-qrcode';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppFooter {
    'start': boolean;
  }
  interface AppFooterAttributes extends StencilHTMLAttributes {
    'start'?: boolean;
  }

  interface AppLogo {}
  interface AppLogoAttributes extends StencilHTMLAttributes {}

  interface AppMenuFooter {}
  interface AppMenuFooterAttributes extends StencilHTMLAttributes {}

  interface AppNavigation {
    'logo': boolean;
    'menuToggle': boolean;
    'navigation': boolean;
  }
  interface AppNavigationAttributes extends StencilHTMLAttributes {
    'logo'?: boolean;
    'menuToggle'?: boolean;
    'navigation'?: boolean;
  }

  interface AppNavigationModal {}
  interface AppNavigationModalAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppComponentsCharts {}
  interface AppComponentsChartsAttributes extends StencilHTMLAttributes {}

  interface AppComponentsGif {}
  interface AppComponentsGifAttributes extends StencilHTMLAttributes {}

  interface AppComponentsHighlightCode {}
  interface AppComponentsHighlightCodeAttributes extends StencilHTMLAttributes {}

  interface AppComponentsInlineEditor {}
  interface AppComponentsInlineEditorAttributes extends StencilHTMLAttributes {}

  interface AppComponentsLazyImg {}
  interface AppComponentsLazyImgAttributes extends StencilHTMLAttributes {}

  interface AppComponentsQrcode {}
  interface AppComponentsQrcodeAttributes extends StencilHTMLAttributes {}

  interface AppComponentsSocial {}
  interface AppComponentsSocialAttributes extends StencilHTMLAttributes {}

  interface AppComponentsYoutube {}
  interface AppComponentsYoutubeAttributes extends StencilHTMLAttributes {}

  interface AppDeckActions {}
  interface AppDeckActionsAttributes extends StencilHTMLAttributes {}

  interface AppDeckBackground {}
  interface AppDeckBackgroundAttributes extends StencilHTMLAttributes {}

  interface AppDeckEvents {}
  interface AppDeckEventsAttributes extends StencilHTMLAttributes {}

  interface AppDeckExtraFeatures {}
  interface AppDeckExtraFeaturesAttributes extends StencilHTMLAttributes {}

  interface AppDeckNavigation {}
  interface AppDeckNavigationAttributes extends StencilHTMLAttributes {}

  interface AppDeckPager {}
  interface AppDeckPagerAttributes extends StencilHTMLAttributes {}

  interface AppDeckSize {}
  interface AppDeckSizeAttributes extends StencilHTMLAttributes {}

  interface AppEditDefault {}
  interface AppEditDefaultAttributes extends StencilHTMLAttributes {}

  interface AppEditFonts {}
  interface AppEditFontsAttributes extends StencilHTMLAttributes {}

  interface AppEditLazyLoading {}
  interface AppEditLazyLoadingAttributes extends StencilHTMLAttributes {}

  interface AppEditMarkdown {}
  interface AppEditMarkdownAttributes extends StencilHTMLAttributes {}

  interface AppEditRtl {}
  interface AppEditRtlAttributes extends StencilHTMLAttributes {}

  interface AppEditTheming {}
  interface AppEditThemingAttributes extends StencilHTMLAttributes {}

  interface AppInstallation {}
  interface AppInstallationAttributes extends StencilHTMLAttributes {}

  interface AppIntroduction {}
  interface AppIntroductionAttributes extends StencilHTMLAttributes {}

  interface AppPublishing {}
  interface AppPublishingAttributes extends StencilHTMLAttributes {}

  interface AppRemoteControl {}
  interface AppRemoteControlAttributes extends StencilHTMLAttributes {}

  interface AppRunning {}
  interface AppRunningAttributes extends StencilHTMLAttributes {}

  interface AppMiscBackstory {}
  interface AppMiscBackstoryAttributes extends StencilHTMLAttributes {}

  interface AppMiscCollections {}
  interface AppMiscCollectionsAttributes extends StencilHTMLAttributes {}

  interface AppMiscLogo {}
  interface AppMiscLogoAttributes extends StencilHTMLAttributes {}

  interface AppMiscOpenSource {}
  interface AppMiscOpenSourceAttributes extends StencilHTMLAttributes {}

  interface AppSlideAuthor {}
  interface AppSlideAuthorAttributes extends StencilHTMLAttributes {}

  interface AppSlideChart {}
  interface AppSlideChartAttributes extends StencilHTMLAttributes {}

  interface AppSlideCode {}
  interface AppSlideCodeAttributes extends StencilHTMLAttributes {}

  interface AppSlideContent {}
  interface AppSlideContentAttributes extends StencilHTMLAttributes {}

  interface AppSlideGif {}
  interface AppSlideGifAttributes extends StencilHTMLAttributes {}

  interface AppSlideQrcode {}
  interface AppSlideQrcodeAttributes extends StencilHTMLAttributes {}

  interface AppSlideSplit {}
  interface AppSlideSplitAttributes extends StencilHTMLAttributes {}

  interface AppSlideTitle {}
  interface AppSlideTitleAttributes extends StencilHTMLAttributes {}

  interface AppSlideYoutube {}
  interface AppSlideYoutubeAttributes extends StencilHTMLAttributes {}

  interface AppSlidesConcept {}
  interface AppSlidesConceptAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppFooter': Components.AppFooter;
    'AppLogo': Components.AppLogo;
    'AppMenuFooter': Components.AppMenuFooter;
    'AppNavigation': Components.AppNavigation;
    'AppNavigationModal': Components.AppNavigationModal;
    'AppHome': Components.AppHome;
    'AppComponentsCharts': Components.AppComponentsCharts;
    'AppComponentsGif': Components.AppComponentsGif;
    'AppComponentsHighlightCode': Components.AppComponentsHighlightCode;
    'AppComponentsInlineEditor': Components.AppComponentsInlineEditor;
    'AppComponentsLazyImg': Components.AppComponentsLazyImg;
    'AppComponentsQrcode': Components.AppComponentsQrcode;
    'AppComponentsSocial': Components.AppComponentsSocial;
    'AppComponentsYoutube': Components.AppComponentsYoutube;
    'AppDeckActions': Components.AppDeckActions;
    'AppDeckBackground': Components.AppDeckBackground;
    'AppDeckEvents': Components.AppDeckEvents;
    'AppDeckExtraFeatures': Components.AppDeckExtraFeatures;
    'AppDeckNavigation': Components.AppDeckNavigation;
    'AppDeckPager': Components.AppDeckPager;
    'AppDeckSize': Components.AppDeckSize;
    'AppEditDefault': Components.AppEditDefault;
    'AppEditFonts': Components.AppEditFonts;
    'AppEditLazyLoading': Components.AppEditLazyLoading;
    'AppEditMarkdown': Components.AppEditMarkdown;
    'AppEditRtl': Components.AppEditRtl;
    'AppEditTheming': Components.AppEditTheming;
    'AppInstallation': Components.AppInstallation;
    'AppIntroduction': Components.AppIntroduction;
    'AppPublishing': Components.AppPublishing;
    'AppRemoteControl': Components.AppRemoteControl;
    'AppRunning': Components.AppRunning;
    'AppMiscBackstory': Components.AppMiscBackstory;
    'AppMiscCollections': Components.AppMiscCollections;
    'AppMiscLogo': Components.AppMiscLogo;
    'AppMiscOpenSource': Components.AppMiscOpenSource;
    'AppSlideAuthor': Components.AppSlideAuthor;
    'AppSlideChart': Components.AppSlideChart;
    'AppSlideCode': Components.AppSlideCode;
    'AppSlideContent': Components.AppSlideContent;
    'AppSlideGif': Components.AppSlideGif;
    'AppSlideQrcode': Components.AppSlideQrcode;
    'AppSlideSplit': Components.AppSlideSplit;
    'AppSlideTitle': Components.AppSlideTitle;
    'AppSlideYoutube': Components.AppSlideYoutube;
    'AppSlidesConcept': Components.AppSlidesConcept;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-logo': Components.AppLogoAttributes;
    'app-menu-footer': Components.AppMenuFooterAttributes;
    'app-navigation': Components.AppNavigationAttributes;
    'app-navigation-modal': Components.AppNavigationModalAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-components-charts': Components.AppComponentsChartsAttributes;
    'app-components-gif': Components.AppComponentsGifAttributes;
    'app-components-highlight-code': Components.AppComponentsHighlightCodeAttributes;
    'app-components-inline-editor': Components.AppComponentsInlineEditorAttributes;
    'app-components-lazy-img': Components.AppComponentsLazyImgAttributes;
    'app-components-qrcode': Components.AppComponentsQrcodeAttributes;
    'app-components-social': Components.AppComponentsSocialAttributes;
    'app-components-youtube': Components.AppComponentsYoutubeAttributes;
    'app-deck-actions': Components.AppDeckActionsAttributes;
    'app-deck-background': Components.AppDeckBackgroundAttributes;
    'app-deck-events': Components.AppDeckEventsAttributes;
    'app-deck-extra-features': Components.AppDeckExtraFeaturesAttributes;
    'app-deck-navigation': Components.AppDeckNavigationAttributes;
    'app-deck-pager': Components.AppDeckPagerAttributes;
    'app-deck-size': Components.AppDeckSizeAttributes;
    'app-edit-default': Components.AppEditDefaultAttributes;
    'app-edit-fonts': Components.AppEditFontsAttributes;
    'app-edit-lazy-loading': Components.AppEditLazyLoadingAttributes;
    'app-edit-markdown': Components.AppEditMarkdownAttributes;
    'app-edit-rtl': Components.AppEditRtlAttributes;
    'app-edit-theming': Components.AppEditThemingAttributes;
    'app-installation': Components.AppInstallationAttributes;
    'app-introduction': Components.AppIntroductionAttributes;
    'app-publishing': Components.AppPublishingAttributes;
    'app-remote-control': Components.AppRemoteControlAttributes;
    'app-running': Components.AppRunningAttributes;
    'app-misc-backstory': Components.AppMiscBackstoryAttributes;
    'app-misc-collections': Components.AppMiscCollectionsAttributes;
    'app-misc-logo': Components.AppMiscLogoAttributes;
    'app-misc-open-source': Components.AppMiscOpenSourceAttributes;
    'app-slide-author': Components.AppSlideAuthorAttributes;
    'app-slide-chart': Components.AppSlideChartAttributes;
    'app-slide-code': Components.AppSlideCodeAttributes;
    'app-slide-content': Components.AppSlideContentAttributes;
    'app-slide-gif': Components.AppSlideGifAttributes;
    'app-slide-qrcode': Components.AppSlideQrcodeAttributes;
    'app-slide-split': Components.AppSlideSplitAttributes;
    'app-slide-title': Components.AppSlideTitleAttributes;
    'app-slide-youtube': Components.AppSlideYoutubeAttributes;
    'app-slides-concept': Components.AppSlidesConceptAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {}
  var HTMLAppLogoElement: {
    prototype: HTMLAppLogoElement;
    new (): HTMLAppLogoElement;
  };

  interface HTMLAppMenuFooterElement extends Components.AppMenuFooter, HTMLStencilElement {}
  var HTMLAppMenuFooterElement: {
    prototype: HTMLAppMenuFooterElement;
    new (): HTMLAppMenuFooterElement;
  };

  interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {}
  var HTMLAppNavigationElement: {
    prototype: HTMLAppNavigationElement;
    new (): HTMLAppNavigationElement;
  };

  interface HTMLAppNavigationModalElement extends Components.AppNavigationModal, HTMLStencilElement {}
  var HTMLAppNavigationModalElement: {
    prototype: HTMLAppNavigationModalElement;
    new (): HTMLAppNavigationModalElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppComponentsChartsElement extends Components.AppComponentsCharts, HTMLStencilElement {}
  var HTMLAppComponentsChartsElement: {
    prototype: HTMLAppComponentsChartsElement;
    new (): HTMLAppComponentsChartsElement;
  };

  interface HTMLAppComponentsGifElement extends Components.AppComponentsGif, HTMLStencilElement {}
  var HTMLAppComponentsGifElement: {
    prototype: HTMLAppComponentsGifElement;
    new (): HTMLAppComponentsGifElement;
  };

  interface HTMLAppComponentsHighlightCodeElement extends Components.AppComponentsHighlightCode, HTMLStencilElement {}
  var HTMLAppComponentsHighlightCodeElement: {
    prototype: HTMLAppComponentsHighlightCodeElement;
    new (): HTMLAppComponentsHighlightCodeElement;
  };

  interface HTMLAppComponentsInlineEditorElement extends Components.AppComponentsInlineEditor, HTMLStencilElement {}
  var HTMLAppComponentsInlineEditorElement: {
    prototype: HTMLAppComponentsInlineEditorElement;
    new (): HTMLAppComponentsInlineEditorElement;
  };

  interface HTMLAppComponentsLazyImgElement extends Components.AppComponentsLazyImg, HTMLStencilElement {}
  var HTMLAppComponentsLazyImgElement: {
    prototype: HTMLAppComponentsLazyImgElement;
    new (): HTMLAppComponentsLazyImgElement;
  };

  interface HTMLAppComponentsQrcodeElement extends Components.AppComponentsQrcode, HTMLStencilElement {}
  var HTMLAppComponentsQrcodeElement: {
    prototype: HTMLAppComponentsQrcodeElement;
    new (): HTMLAppComponentsQrcodeElement;
  };

  interface HTMLAppComponentsSocialElement extends Components.AppComponentsSocial, HTMLStencilElement {}
  var HTMLAppComponentsSocialElement: {
    prototype: HTMLAppComponentsSocialElement;
    new (): HTMLAppComponentsSocialElement;
  };

  interface HTMLAppComponentsYoutubeElement extends Components.AppComponentsYoutube, HTMLStencilElement {}
  var HTMLAppComponentsYoutubeElement: {
    prototype: HTMLAppComponentsYoutubeElement;
    new (): HTMLAppComponentsYoutubeElement;
  };

  interface HTMLAppDeckActionsElement extends Components.AppDeckActions, HTMLStencilElement {}
  var HTMLAppDeckActionsElement: {
    prototype: HTMLAppDeckActionsElement;
    new (): HTMLAppDeckActionsElement;
  };

  interface HTMLAppDeckBackgroundElement extends Components.AppDeckBackground, HTMLStencilElement {}
  var HTMLAppDeckBackgroundElement: {
    prototype: HTMLAppDeckBackgroundElement;
    new (): HTMLAppDeckBackgroundElement;
  };

  interface HTMLAppDeckEventsElement extends Components.AppDeckEvents, HTMLStencilElement {}
  var HTMLAppDeckEventsElement: {
    prototype: HTMLAppDeckEventsElement;
    new (): HTMLAppDeckEventsElement;
  };

  interface HTMLAppDeckExtraFeaturesElement extends Components.AppDeckExtraFeatures, HTMLStencilElement {}
  var HTMLAppDeckExtraFeaturesElement: {
    prototype: HTMLAppDeckExtraFeaturesElement;
    new (): HTMLAppDeckExtraFeaturesElement;
  };

  interface HTMLAppDeckNavigationElement extends Components.AppDeckNavigation, HTMLStencilElement {}
  var HTMLAppDeckNavigationElement: {
    prototype: HTMLAppDeckNavigationElement;
    new (): HTMLAppDeckNavigationElement;
  };

  interface HTMLAppDeckPagerElement extends Components.AppDeckPager, HTMLStencilElement {}
  var HTMLAppDeckPagerElement: {
    prototype: HTMLAppDeckPagerElement;
    new (): HTMLAppDeckPagerElement;
  };

  interface HTMLAppDeckSizeElement extends Components.AppDeckSize, HTMLStencilElement {}
  var HTMLAppDeckSizeElement: {
    prototype: HTMLAppDeckSizeElement;
    new (): HTMLAppDeckSizeElement;
  };

  interface HTMLAppEditDefaultElement extends Components.AppEditDefault, HTMLStencilElement {}
  var HTMLAppEditDefaultElement: {
    prototype: HTMLAppEditDefaultElement;
    new (): HTMLAppEditDefaultElement;
  };

  interface HTMLAppEditFontsElement extends Components.AppEditFonts, HTMLStencilElement {}
  var HTMLAppEditFontsElement: {
    prototype: HTMLAppEditFontsElement;
    new (): HTMLAppEditFontsElement;
  };

  interface HTMLAppEditLazyLoadingElement extends Components.AppEditLazyLoading, HTMLStencilElement {}
  var HTMLAppEditLazyLoadingElement: {
    prototype: HTMLAppEditLazyLoadingElement;
    new (): HTMLAppEditLazyLoadingElement;
  };

  interface HTMLAppEditMarkdownElement extends Components.AppEditMarkdown, HTMLStencilElement {}
  var HTMLAppEditMarkdownElement: {
    prototype: HTMLAppEditMarkdownElement;
    new (): HTMLAppEditMarkdownElement;
  };

  interface HTMLAppEditRtlElement extends Components.AppEditRtl, HTMLStencilElement {}
  var HTMLAppEditRtlElement: {
    prototype: HTMLAppEditRtlElement;
    new (): HTMLAppEditRtlElement;
  };

  interface HTMLAppEditThemingElement extends Components.AppEditTheming, HTMLStencilElement {}
  var HTMLAppEditThemingElement: {
    prototype: HTMLAppEditThemingElement;
    new (): HTMLAppEditThemingElement;
  };

  interface HTMLAppInstallationElement extends Components.AppInstallation, HTMLStencilElement {}
  var HTMLAppInstallationElement: {
    prototype: HTMLAppInstallationElement;
    new (): HTMLAppInstallationElement;
  };

  interface HTMLAppIntroductionElement extends Components.AppIntroduction, HTMLStencilElement {}
  var HTMLAppIntroductionElement: {
    prototype: HTMLAppIntroductionElement;
    new (): HTMLAppIntroductionElement;
  };

  interface HTMLAppPublishingElement extends Components.AppPublishing, HTMLStencilElement {}
  var HTMLAppPublishingElement: {
    prototype: HTMLAppPublishingElement;
    new (): HTMLAppPublishingElement;
  };

  interface HTMLAppRemoteControlElement extends Components.AppRemoteControl, HTMLStencilElement {}
  var HTMLAppRemoteControlElement: {
    prototype: HTMLAppRemoteControlElement;
    new (): HTMLAppRemoteControlElement;
  };

  interface HTMLAppRunningElement extends Components.AppRunning, HTMLStencilElement {}
  var HTMLAppRunningElement: {
    prototype: HTMLAppRunningElement;
    new (): HTMLAppRunningElement;
  };

  interface HTMLAppMiscBackstoryElement extends Components.AppMiscBackstory, HTMLStencilElement {}
  var HTMLAppMiscBackstoryElement: {
    prototype: HTMLAppMiscBackstoryElement;
    new (): HTMLAppMiscBackstoryElement;
  };

  interface HTMLAppMiscCollectionsElement extends Components.AppMiscCollections, HTMLStencilElement {}
  var HTMLAppMiscCollectionsElement: {
    prototype: HTMLAppMiscCollectionsElement;
    new (): HTMLAppMiscCollectionsElement;
  };

  interface HTMLAppMiscLogoElement extends Components.AppMiscLogo, HTMLStencilElement {}
  var HTMLAppMiscLogoElement: {
    prototype: HTMLAppMiscLogoElement;
    new (): HTMLAppMiscLogoElement;
  };

  interface HTMLAppMiscOpenSourceElement extends Components.AppMiscOpenSource, HTMLStencilElement {}
  var HTMLAppMiscOpenSourceElement: {
    prototype: HTMLAppMiscOpenSourceElement;
    new (): HTMLAppMiscOpenSourceElement;
  };

  interface HTMLAppSlideAuthorElement extends Components.AppSlideAuthor, HTMLStencilElement {}
  var HTMLAppSlideAuthorElement: {
    prototype: HTMLAppSlideAuthorElement;
    new (): HTMLAppSlideAuthorElement;
  };

  interface HTMLAppSlideChartElement extends Components.AppSlideChart, HTMLStencilElement {}
  var HTMLAppSlideChartElement: {
    prototype: HTMLAppSlideChartElement;
    new (): HTMLAppSlideChartElement;
  };

  interface HTMLAppSlideCodeElement extends Components.AppSlideCode, HTMLStencilElement {}
  var HTMLAppSlideCodeElement: {
    prototype: HTMLAppSlideCodeElement;
    new (): HTMLAppSlideCodeElement;
  };

  interface HTMLAppSlideContentElement extends Components.AppSlideContent, HTMLStencilElement {}
  var HTMLAppSlideContentElement: {
    prototype: HTMLAppSlideContentElement;
    new (): HTMLAppSlideContentElement;
  };

  interface HTMLAppSlideGifElement extends Components.AppSlideGif, HTMLStencilElement {}
  var HTMLAppSlideGifElement: {
    prototype: HTMLAppSlideGifElement;
    new (): HTMLAppSlideGifElement;
  };

  interface HTMLAppSlideQrcodeElement extends Components.AppSlideQrcode, HTMLStencilElement {}
  var HTMLAppSlideQrcodeElement: {
    prototype: HTMLAppSlideQrcodeElement;
    new (): HTMLAppSlideQrcodeElement;
  };

  interface HTMLAppSlideSplitElement extends Components.AppSlideSplit, HTMLStencilElement {}
  var HTMLAppSlideSplitElement: {
    prototype: HTMLAppSlideSplitElement;
    new (): HTMLAppSlideSplitElement;
  };

  interface HTMLAppSlideTitleElement extends Components.AppSlideTitle, HTMLStencilElement {}
  var HTMLAppSlideTitleElement: {
    prototype: HTMLAppSlideTitleElement;
    new (): HTMLAppSlideTitleElement;
  };

  interface HTMLAppSlideYoutubeElement extends Components.AppSlideYoutube, HTMLStencilElement {}
  var HTMLAppSlideYoutubeElement: {
    prototype: HTMLAppSlideYoutubeElement;
    new (): HTMLAppSlideYoutubeElement;
  };

  interface HTMLAppSlidesConceptElement extends Components.AppSlidesConcept, HTMLStencilElement {}
  var HTMLAppSlidesConceptElement: {
    prototype: HTMLAppSlidesConceptElement;
    new (): HTMLAppSlidesConceptElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-footer': HTMLAppFooterElement
    'app-logo': HTMLAppLogoElement
    'app-menu-footer': HTMLAppMenuFooterElement
    'app-navigation': HTMLAppNavigationElement
    'app-navigation-modal': HTMLAppNavigationModalElement
    'app-home': HTMLAppHomeElement
    'app-components-charts': HTMLAppComponentsChartsElement
    'app-components-gif': HTMLAppComponentsGifElement
    'app-components-highlight-code': HTMLAppComponentsHighlightCodeElement
    'app-components-inline-editor': HTMLAppComponentsInlineEditorElement
    'app-components-lazy-img': HTMLAppComponentsLazyImgElement
    'app-components-qrcode': HTMLAppComponentsQrcodeElement
    'app-components-social': HTMLAppComponentsSocialElement
    'app-components-youtube': HTMLAppComponentsYoutubeElement
    'app-deck-actions': HTMLAppDeckActionsElement
    'app-deck-background': HTMLAppDeckBackgroundElement
    'app-deck-events': HTMLAppDeckEventsElement
    'app-deck-extra-features': HTMLAppDeckExtraFeaturesElement
    'app-deck-navigation': HTMLAppDeckNavigationElement
    'app-deck-pager': HTMLAppDeckPagerElement
    'app-deck-size': HTMLAppDeckSizeElement
    'app-edit-default': HTMLAppEditDefaultElement
    'app-edit-fonts': HTMLAppEditFontsElement
    'app-edit-lazy-loading': HTMLAppEditLazyLoadingElement
    'app-edit-markdown': HTMLAppEditMarkdownElement
    'app-edit-rtl': HTMLAppEditRtlElement
    'app-edit-theming': HTMLAppEditThemingElement
    'app-installation': HTMLAppInstallationElement
    'app-introduction': HTMLAppIntroductionElement
    'app-publishing': HTMLAppPublishingElement
    'app-remote-control': HTMLAppRemoteControlElement
    'app-running': HTMLAppRunningElement
    'app-misc-backstory': HTMLAppMiscBackstoryElement
    'app-misc-collections': HTMLAppMiscCollectionsElement
    'app-misc-logo': HTMLAppMiscLogoElement
    'app-misc-open-source': HTMLAppMiscOpenSourceElement
    'app-slide-author': HTMLAppSlideAuthorElement
    'app-slide-chart': HTMLAppSlideChartElement
    'app-slide-code': HTMLAppSlideCodeElement
    'app-slide-content': HTMLAppSlideContentElement
    'app-slide-gif': HTMLAppSlideGifElement
    'app-slide-qrcode': HTMLAppSlideQrcodeElement
    'app-slide-split': HTMLAppSlideSplitElement
    'app-slide-title': HTMLAppSlideTitleElement
    'app-slide-youtube': HTMLAppSlideYoutubeElement
    'app-slides-concept': HTMLAppSlidesConceptElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-footer': HTMLAppFooterElement;
    'app-logo': HTMLAppLogoElement;
    'app-menu-footer': HTMLAppMenuFooterElement;
    'app-navigation': HTMLAppNavigationElement;
    'app-navigation-modal': HTMLAppNavigationModalElement;
    'app-home': HTMLAppHomeElement;
    'app-components-charts': HTMLAppComponentsChartsElement;
    'app-components-gif': HTMLAppComponentsGifElement;
    'app-components-highlight-code': HTMLAppComponentsHighlightCodeElement;
    'app-components-inline-editor': HTMLAppComponentsInlineEditorElement;
    'app-components-lazy-img': HTMLAppComponentsLazyImgElement;
    'app-components-qrcode': HTMLAppComponentsQrcodeElement;
    'app-components-social': HTMLAppComponentsSocialElement;
    'app-components-youtube': HTMLAppComponentsYoutubeElement;
    'app-deck-actions': HTMLAppDeckActionsElement;
    'app-deck-background': HTMLAppDeckBackgroundElement;
    'app-deck-events': HTMLAppDeckEventsElement;
    'app-deck-extra-features': HTMLAppDeckExtraFeaturesElement;
    'app-deck-navigation': HTMLAppDeckNavigationElement;
    'app-deck-pager': HTMLAppDeckPagerElement;
    'app-deck-size': HTMLAppDeckSizeElement;
    'app-edit-default': HTMLAppEditDefaultElement;
    'app-edit-fonts': HTMLAppEditFontsElement;
    'app-edit-lazy-loading': HTMLAppEditLazyLoadingElement;
    'app-edit-markdown': HTMLAppEditMarkdownElement;
    'app-edit-rtl': HTMLAppEditRtlElement;
    'app-edit-theming': HTMLAppEditThemingElement;
    'app-installation': HTMLAppInstallationElement;
    'app-introduction': HTMLAppIntroductionElement;
    'app-publishing': HTMLAppPublishingElement;
    'app-remote-control': HTMLAppRemoteControlElement;
    'app-running': HTMLAppRunningElement;
    'app-misc-backstory': HTMLAppMiscBackstoryElement;
    'app-misc-collections': HTMLAppMiscCollectionsElement;
    'app-misc-logo': HTMLAppMiscLogoElement;
    'app-misc-open-source': HTMLAppMiscOpenSourceElement;
    'app-slide-author': HTMLAppSlideAuthorElement;
    'app-slide-chart': HTMLAppSlideChartElement;
    'app-slide-code': HTMLAppSlideCodeElement;
    'app-slide-content': HTMLAppSlideContentElement;
    'app-slide-gif': HTMLAppSlideGifElement;
    'app-slide-qrcode': HTMLAppSlideQrcodeElement;
    'app-slide-split': HTMLAppSlideSplitElement;
    'app-slide-title': HTMLAppSlideTitleElement;
    'app-slide-youtube': HTMLAppSlideYoutubeElement;
    'app-slides-concept': HTMLAppSlidesConceptElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
