/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppComponentsCharts {}
  interface AppComponentsColor {}
  interface AppComponentsGif {}
  interface AppComponentsHighlightCode {}
  interface AppComponentsInlineEditor {}
  interface AppComponentsLazyImg {}
  interface AppComponentsQrcode {}
  interface AppComponentsSocial {}
  interface AppComponentsYoutube {}
  interface AppDeckActions {}
  interface AppDeckBackground {}
  interface AppDeckEvents {}
  interface AppDeckExtraFeatures {}
  interface AppDeckNavigation {}
  interface AppDeckPager {}
  interface AppDeckSize {}
  interface AppEditDefault {}
  interface AppEditFonts {}
  interface AppEditLazyLoading {}
  interface AppEditMarkdown {}
  interface AppEditReveal {}
  interface AppEditRtl {}
  interface AppEditTheming {}
  interface AppFooter {
    'start': boolean;
  }
  interface AppHome {}
  interface AppInstallation {}
  interface AppIntroduction {}
  interface AppLogo {}
  interface AppMenuFooter {}
  interface AppMiscBackstory {}
  interface AppMiscCollections {}
  interface AppMiscContact {}
  interface AppMiscLogo {}
  interface AppMiscOpenSource {}
  interface AppNavigation {
    'logo': boolean;
    'menuToggle': boolean;
    'navigation': boolean;
  }
  interface AppNavigationModal {}
  interface AppPublishing {}
  interface AppRemoteControl {}
  interface AppRoot {}
  interface AppRunning {}
  interface AppSlideAuthor {}
  interface AppSlideBigImg {}
  interface AppSlideChart {}
  interface AppSlideCode {}
  interface AppSlideContent {}
  interface AppSlideCountdown {}
  interface AppSlideGif {}
  interface AppSlideQrcode {}
  interface AppSlideSplit {}
  interface AppSlideTitle {}
  interface AppSlideVideo {}
  interface AppSlideYoutube {}
  interface AppSlidesConcept {}
  interface AppThemeSwitcher {}
}

declare global {


  interface HTMLAppComponentsChartsElement extends Components.AppComponentsCharts, HTMLStencilElement {}
  const HTMLAppComponentsChartsElement: {
    prototype: HTMLAppComponentsChartsElement;
    new (): HTMLAppComponentsChartsElement;
  };

  interface HTMLAppComponentsColorElement extends Components.AppComponentsColor, HTMLStencilElement {}
  const HTMLAppComponentsColorElement: {
    prototype: HTMLAppComponentsColorElement;
    new (): HTMLAppComponentsColorElement;
  };

  interface HTMLAppComponentsGifElement extends Components.AppComponentsGif, HTMLStencilElement {}
  const HTMLAppComponentsGifElement: {
    prototype: HTMLAppComponentsGifElement;
    new (): HTMLAppComponentsGifElement;
  };

  interface HTMLAppComponentsHighlightCodeElement extends Components.AppComponentsHighlightCode, HTMLStencilElement {}
  const HTMLAppComponentsHighlightCodeElement: {
    prototype: HTMLAppComponentsHighlightCodeElement;
    new (): HTMLAppComponentsHighlightCodeElement;
  };

  interface HTMLAppComponentsInlineEditorElement extends Components.AppComponentsInlineEditor, HTMLStencilElement {}
  const HTMLAppComponentsInlineEditorElement: {
    prototype: HTMLAppComponentsInlineEditorElement;
    new (): HTMLAppComponentsInlineEditorElement;
  };

  interface HTMLAppComponentsLazyImgElement extends Components.AppComponentsLazyImg, HTMLStencilElement {}
  const HTMLAppComponentsLazyImgElement: {
    prototype: HTMLAppComponentsLazyImgElement;
    new (): HTMLAppComponentsLazyImgElement;
  };

  interface HTMLAppComponentsQrcodeElement extends Components.AppComponentsQrcode, HTMLStencilElement {}
  const HTMLAppComponentsQrcodeElement: {
    prototype: HTMLAppComponentsQrcodeElement;
    new (): HTMLAppComponentsQrcodeElement;
  };

  interface HTMLAppComponentsSocialElement extends Components.AppComponentsSocial, HTMLStencilElement {}
  const HTMLAppComponentsSocialElement: {
    prototype: HTMLAppComponentsSocialElement;
    new (): HTMLAppComponentsSocialElement;
  };

  interface HTMLAppComponentsYoutubeElement extends Components.AppComponentsYoutube, HTMLStencilElement {}
  const HTMLAppComponentsYoutubeElement: {
    prototype: HTMLAppComponentsYoutubeElement;
    new (): HTMLAppComponentsYoutubeElement;
  };

  interface HTMLAppDeckActionsElement extends Components.AppDeckActions, HTMLStencilElement {}
  const HTMLAppDeckActionsElement: {
    prototype: HTMLAppDeckActionsElement;
    new (): HTMLAppDeckActionsElement;
  };

  interface HTMLAppDeckBackgroundElement extends Components.AppDeckBackground, HTMLStencilElement {}
  const HTMLAppDeckBackgroundElement: {
    prototype: HTMLAppDeckBackgroundElement;
    new (): HTMLAppDeckBackgroundElement;
  };

  interface HTMLAppDeckEventsElement extends Components.AppDeckEvents, HTMLStencilElement {}
  const HTMLAppDeckEventsElement: {
    prototype: HTMLAppDeckEventsElement;
    new (): HTMLAppDeckEventsElement;
  };

  interface HTMLAppDeckExtraFeaturesElement extends Components.AppDeckExtraFeatures, HTMLStencilElement {}
  const HTMLAppDeckExtraFeaturesElement: {
    prototype: HTMLAppDeckExtraFeaturesElement;
    new (): HTMLAppDeckExtraFeaturesElement;
  };

  interface HTMLAppDeckNavigationElement extends Components.AppDeckNavigation, HTMLStencilElement {}
  const HTMLAppDeckNavigationElement: {
    prototype: HTMLAppDeckNavigationElement;
    new (): HTMLAppDeckNavigationElement;
  };

  interface HTMLAppDeckPagerElement extends Components.AppDeckPager, HTMLStencilElement {}
  const HTMLAppDeckPagerElement: {
    prototype: HTMLAppDeckPagerElement;
    new (): HTMLAppDeckPagerElement;
  };

  interface HTMLAppDeckSizeElement extends Components.AppDeckSize, HTMLStencilElement {}
  const HTMLAppDeckSizeElement: {
    prototype: HTMLAppDeckSizeElement;
    new (): HTMLAppDeckSizeElement;
  };

  interface HTMLAppEditDefaultElement extends Components.AppEditDefault, HTMLStencilElement {}
  const HTMLAppEditDefaultElement: {
    prototype: HTMLAppEditDefaultElement;
    new (): HTMLAppEditDefaultElement;
  };

  interface HTMLAppEditFontsElement extends Components.AppEditFonts, HTMLStencilElement {}
  const HTMLAppEditFontsElement: {
    prototype: HTMLAppEditFontsElement;
    new (): HTMLAppEditFontsElement;
  };

  interface HTMLAppEditLazyLoadingElement extends Components.AppEditLazyLoading, HTMLStencilElement {}
  const HTMLAppEditLazyLoadingElement: {
    prototype: HTMLAppEditLazyLoadingElement;
    new (): HTMLAppEditLazyLoadingElement;
  };

  interface HTMLAppEditMarkdownElement extends Components.AppEditMarkdown, HTMLStencilElement {}
  const HTMLAppEditMarkdownElement: {
    prototype: HTMLAppEditMarkdownElement;
    new (): HTMLAppEditMarkdownElement;
  };

  interface HTMLAppEditRevealElement extends Components.AppEditReveal, HTMLStencilElement {}
  const HTMLAppEditRevealElement: {
    prototype: HTMLAppEditRevealElement;
    new (): HTMLAppEditRevealElement;
  };

  interface HTMLAppEditRtlElement extends Components.AppEditRtl, HTMLStencilElement {}
  const HTMLAppEditRtlElement: {
    prototype: HTMLAppEditRtlElement;
    new (): HTMLAppEditRtlElement;
  };

  interface HTMLAppEditThemingElement extends Components.AppEditTheming, HTMLStencilElement {}
  const HTMLAppEditThemingElement: {
    prototype: HTMLAppEditThemingElement;
    new (): HTMLAppEditThemingElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  const HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  const HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppInstallationElement extends Components.AppInstallation, HTMLStencilElement {}
  const HTMLAppInstallationElement: {
    prototype: HTMLAppInstallationElement;
    new (): HTMLAppInstallationElement;
  };

  interface HTMLAppIntroductionElement extends Components.AppIntroduction, HTMLStencilElement {}
  const HTMLAppIntroductionElement: {
    prototype: HTMLAppIntroductionElement;
    new (): HTMLAppIntroductionElement;
  };

  interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {}
  const HTMLAppLogoElement: {
    prototype: HTMLAppLogoElement;
    new (): HTMLAppLogoElement;
  };

  interface HTMLAppMenuFooterElement extends Components.AppMenuFooter, HTMLStencilElement {}
  const HTMLAppMenuFooterElement: {
    prototype: HTMLAppMenuFooterElement;
    new (): HTMLAppMenuFooterElement;
  };

  interface HTMLAppMiscBackstoryElement extends Components.AppMiscBackstory, HTMLStencilElement {}
  const HTMLAppMiscBackstoryElement: {
    prototype: HTMLAppMiscBackstoryElement;
    new (): HTMLAppMiscBackstoryElement;
  };

  interface HTMLAppMiscCollectionsElement extends Components.AppMiscCollections, HTMLStencilElement {}
  const HTMLAppMiscCollectionsElement: {
    prototype: HTMLAppMiscCollectionsElement;
    new (): HTMLAppMiscCollectionsElement;
  };

  interface HTMLAppMiscContactElement extends Components.AppMiscContact, HTMLStencilElement {}
  const HTMLAppMiscContactElement: {
    prototype: HTMLAppMiscContactElement;
    new (): HTMLAppMiscContactElement;
  };

  interface HTMLAppMiscLogoElement extends Components.AppMiscLogo, HTMLStencilElement {}
  const HTMLAppMiscLogoElement: {
    prototype: HTMLAppMiscLogoElement;
    new (): HTMLAppMiscLogoElement;
  };

  interface HTMLAppMiscOpenSourceElement extends Components.AppMiscOpenSource, HTMLStencilElement {}
  const HTMLAppMiscOpenSourceElement: {
    prototype: HTMLAppMiscOpenSourceElement;
    new (): HTMLAppMiscOpenSourceElement;
  };

  interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {}
  const HTMLAppNavigationElement: {
    prototype: HTMLAppNavigationElement;
    new (): HTMLAppNavigationElement;
  };

  interface HTMLAppNavigationModalElement extends Components.AppNavigationModal, HTMLStencilElement {}
  const HTMLAppNavigationModalElement: {
    prototype: HTMLAppNavigationModalElement;
    new (): HTMLAppNavigationModalElement;
  };

  interface HTMLAppPublishingElement extends Components.AppPublishing, HTMLStencilElement {}
  const HTMLAppPublishingElement: {
    prototype: HTMLAppPublishingElement;
    new (): HTMLAppPublishingElement;
  };

  interface HTMLAppRemoteControlElement extends Components.AppRemoteControl, HTMLStencilElement {}
  const HTMLAppRemoteControlElement: {
    prototype: HTMLAppRemoteControlElement;
    new (): HTMLAppRemoteControlElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  const HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppRunningElement extends Components.AppRunning, HTMLStencilElement {}
  const HTMLAppRunningElement: {
    prototype: HTMLAppRunningElement;
    new (): HTMLAppRunningElement;
  };

  interface HTMLAppSlideAuthorElement extends Components.AppSlideAuthor, HTMLStencilElement {}
  const HTMLAppSlideAuthorElement: {
    prototype: HTMLAppSlideAuthorElement;
    new (): HTMLAppSlideAuthorElement;
  };

  interface HTMLAppSlideBigImgElement extends Components.AppSlideBigImg, HTMLStencilElement {}
  const HTMLAppSlideBigImgElement: {
    prototype: HTMLAppSlideBigImgElement;
    new (): HTMLAppSlideBigImgElement;
  };

  interface HTMLAppSlideChartElement extends Components.AppSlideChart, HTMLStencilElement {}
  const HTMLAppSlideChartElement: {
    prototype: HTMLAppSlideChartElement;
    new (): HTMLAppSlideChartElement;
  };

  interface HTMLAppSlideCodeElement extends Components.AppSlideCode, HTMLStencilElement {}
  const HTMLAppSlideCodeElement: {
    prototype: HTMLAppSlideCodeElement;
    new (): HTMLAppSlideCodeElement;
  };

  interface HTMLAppSlideContentElement extends Components.AppSlideContent, HTMLStencilElement {}
  const HTMLAppSlideContentElement: {
    prototype: HTMLAppSlideContentElement;
    new (): HTMLAppSlideContentElement;
  };

  interface HTMLAppSlideCountdownElement extends Components.AppSlideCountdown, HTMLStencilElement {}
  const HTMLAppSlideCountdownElement: {
    prototype: HTMLAppSlideCountdownElement;
    new (): HTMLAppSlideCountdownElement;
  };

  interface HTMLAppSlideGifElement extends Components.AppSlideGif, HTMLStencilElement {}
  const HTMLAppSlideGifElement: {
    prototype: HTMLAppSlideGifElement;
    new (): HTMLAppSlideGifElement;
  };

  interface HTMLAppSlideQrcodeElement extends Components.AppSlideQrcode, HTMLStencilElement {}
  const HTMLAppSlideQrcodeElement: {
    prototype: HTMLAppSlideQrcodeElement;
    new (): HTMLAppSlideQrcodeElement;
  };

  interface HTMLAppSlideSplitElement extends Components.AppSlideSplit, HTMLStencilElement {}
  const HTMLAppSlideSplitElement: {
    prototype: HTMLAppSlideSplitElement;
    new (): HTMLAppSlideSplitElement;
  };

  interface HTMLAppSlideTitleElement extends Components.AppSlideTitle, HTMLStencilElement {}
  const HTMLAppSlideTitleElement: {
    prototype: HTMLAppSlideTitleElement;
    new (): HTMLAppSlideTitleElement;
  };

  interface HTMLAppSlideVideoElement extends Components.AppSlideVideo, HTMLStencilElement {}
  const HTMLAppSlideVideoElement: {
    prototype: HTMLAppSlideVideoElement;
    new (): HTMLAppSlideVideoElement;
  };

  interface HTMLAppSlideYoutubeElement extends Components.AppSlideYoutube, HTMLStencilElement {}
  const HTMLAppSlideYoutubeElement: {
    prototype: HTMLAppSlideYoutubeElement;
    new (): HTMLAppSlideYoutubeElement;
  };

  interface HTMLAppSlidesConceptElement extends Components.AppSlidesConcept, HTMLStencilElement {}
  const HTMLAppSlidesConceptElement: {
    prototype: HTMLAppSlidesConceptElement;
    new (): HTMLAppSlidesConceptElement;
  };

  interface HTMLAppThemeSwitcherElement extends Components.AppThemeSwitcher, HTMLStencilElement {}
  const HTMLAppThemeSwitcherElement: {
    prototype: HTMLAppThemeSwitcherElement;
    new (): HTMLAppThemeSwitcherElement;
  };
  interface HTMLElementTagNameMap {
    'app-components-charts': HTMLAppComponentsChartsElement;
    'app-components-color': HTMLAppComponentsColorElement;
    'app-components-gif': HTMLAppComponentsGifElement;
    'app-components-highlight-code': HTMLAppComponentsHighlightCodeElement;
    'app-components-inline-editor': HTMLAppComponentsInlineEditorElement;
    'app-components-lazy-img': HTMLAppComponentsLazyImgElement;
    'app-components-qrcode': HTMLAppComponentsQrcodeElement;
    'app-components-social': HTMLAppComponentsSocialElement;
    'app-components-youtube': HTMLAppComponentsYoutubeElement;
    'app-deck-actions': HTMLAppDeckActionsElement;
    'app-deck-background': HTMLAppDeckBackgroundElement;
    'app-deck-events': HTMLAppDeckEventsElement;
    'app-deck-extra-features': HTMLAppDeckExtraFeaturesElement;
    'app-deck-navigation': HTMLAppDeckNavigationElement;
    'app-deck-pager': HTMLAppDeckPagerElement;
    'app-deck-size': HTMLAppDeckSizeElement;
    'app-edit-default': HTMLAppEditDefaultElement;
    'app-edit-fonts': HTMLAppEditFontsElement;
    'app-edit-lazy-loading': HTMLAppEditLazyLoadingElement;
    'app-edit-markdown': HTMLAppEditMarkdownElement;
    'app-edit-reveal': HTMLAppEditRevealElement;
    'app-edit-rtl': HTMLAppEditRtlElement;
    'app-edit-theming': HTMLAppEditThemingElement;
    'app-footer': HTMLAppFooterElement;
    'app-home': HTMLAppHomeElement;
    'app-installation': HTMLAppInstallationElement;
    'app-introduction': HTMLAppIntroductionElement;
    'app-logo': HTMLAppLogoElement;
    'app-menu-footer': HTMLAppMenuFooterElement;
    'app-misc-backstory': HTMLAppMiscBackstoryElement;
    'app-misc-collections': HTMLAppMiscCollectionsElement;
    'app-misc-contact': HTMLAppMiscContactElement;
    'app-misc-logo': HTMLAppMiscLogoElement;
    'app-misc-open-source': HTMLAppMiscOpenSourceElement;
    'app-navigation': HTMLAppNavigationElement;
    'app-navigation-modal': HTMLAppNavigationModalElement;
    'app-publishing': HTMLAppPublishingElement;
    'app-remote-control': HTMLAppRemoteControlElement;
    'app-root': HTMLAppRootElement;
    'app-running': HTMLAppRunningElement;
    'app-slide-author': HTMLAppSlideAuthorElement;
    'app-slide-big-img': HTMLAppSlideBigImgElement;
    'app-slide-chart': HTMLAppSlideChartElement;
    'app-slide-code': HTMLAppSlideCodeElement;
    'app-slide-content': HTMLAppSlideContentElement;
    'app-slide-countdown': HTMLAppSlideCountdownElement;
    'app-slide-gif': HTMLAppSlideGifElement;
    'app-slide-qrcode': HTMLAppSlideQrcodeElement;
    'app-slide-split': HTMLAppSlideSplitElement;
    'app-slide-title': HTMLAppSlideTitleElement;
    'app-slide-video': HTMLAppSlideVideoElement;
    'app-slide-youtube': HTMLAppSlideYoutubeElement;
    'app-slides-concept': HTMLAppSlidesConceptElement;
    'app-theme-switcher': HTMLAppThemeSwitcherElement;
  }
}

declare namespace LocalJSX {
  interface AppComponentsCharts {}
  interface AppComponentsColor {}
  interface AppComponentsGif {}
  interface AppComponentsHighlightCode {}
  interface AppComponentsInlineEditor {}
  interface AppComponentsLazyImg {}
  interface AppComponentsQrcode {}
  interface AppComponentsSocial {}
  interface AppComponentsYoutube {}
  interface AppDeckActions {}
  interface AppDeckBackground {}
  interface AppDeckEvents {}
  interface AppDeckExtraFeatures {}
  interface AppDeckNavigation {}
  interface AppDeckPager {}
  interface AppDeckSize {}
  interface AppEditDefault {}
  interface AppEditFonts {}
  interface AppEditLazyLoading {}
  interface AppEditMarkdown {}
  interface AppEditReveal {}
  interface AppEditRtl {}
  interface AppEditTheming {}
  interface AppFooter {
    'start'?: boolean;
  }
  interface AppHome {}
  interface AppInstallation {}
  interface AppIntroduction {}
  interface AppLogo {}
  interface AppMenuFooter {}
  interface AppMiscBackstory {}
  interface AppMiscCollections {}
  interface AppMiscContact {}
  interface AppMiscLogo {}
  interface AppMiscOpenSource {}
  interface AppNavigation {
    'logo'?: boolean;
    'menuToggle'?: boolean;
    'navigation'?: boolean;
  }
  interface AppNavigationModal {}
  interface AppPublishing {}
  interface AppRemoteControl {}
  interface AppRoot {}
  interface AppRunning {}
  interface AppSlideAuthor {}
  interface AppSlideBigImg {}
  interface AppSlideChart {}
  interface AppSlideCode {}
  interface AppSlideContent {}
  interface AppSlideCountdown {}
  interface AppSlideGif {}
  interface AppSlideQrcode {}
  interface AppSlideSplit {}
  interface AppSlideTitle {}
  interface AppSlideVideo {}
  interface AppSlideYoutube {}
  interface AppSlidesConcept {}
  interface AppThemeSwitcher {}

  interface IntrinsicElements {
    'app-components-charts': AppComponentsCharts;
    'app-components-color': AppComponentsColor;
    'app-components-gif': AppComponentsGif;
    'app-components-highlight-code': AppComponentsHighlightCode;
    'app-components-inline-editor': AppComponentsInlineEditor;
    'app-components-lazy-img': AppComponentsLazyImg;
    'app-components-qrcode': AppComponentsQrcode;
    'app-components-social': AppComponentsSocial;
    'app-components-youtube': AppComponentsYoutube;
    'app-deck-actions': AppDeckActions;
    'app-deck-background': AppDeckBackground;
    'app-deck-events': AppDeckEvents;
    'app-deck-extra-features': AppDeckExtraFeatures;
    'app-deck-navigation': AppDeckNavigation;
    'app-deck-pager': AppDeckPager;
    'app-deck-size': AppDeckSize;
    'app-edit-default': AppEditDefault;
    'app-edit-fonts': AppEditFonts;
    'app-edit-lazy-loading': AppEditLazyLoading;
    'app-edit-markdown': AppEditMarkdown;
    'app-edit-reveal': AppEditReveal;
    'app-edit-rtl': AppEditRtl;
    'app-edit-theming': AppEditTheming;
    'app-footer': AppFooter;
    'app-home': AppHome;
    'app-installation': AppInstallation;
    'app-introduction': AppIntroduction;
    'app-logo': AppLogo;
    'app-menu-footer': AppMenuFooter;
    'app-misc-backstory': AppMiscBackstory;
    'app-misc-collections': AppMiscCollections;
    'app-misc-contact': AppMiscContact;
    'app-misc-logo': AppMiscLogo;
    'app-misc-open-source': AppMiscOpenSource;
    'app-navigation': AppNavigation;
    'app-navigation-modal': AppNavigationModal;
    'app-publishing': AppPublishing;
    'app-remote-control': AppRemoteControl;
    'app-root': AppRoot;
    'app-running': AppRunning;
    'app-slide-author': AppSlideAuthor;
    'app-slide-big-img': AppSlideBigImg;
    'app-slide-chart': AppSlideChart;
    'app-slide-code': AppSlideCode;
    'app-slide-content': AppSlideContent;
    'app-slide-countdown': AppSlideCountdown;
    'app-slide-gif': AppSlideGif;
    'app-slide-qrcode': AppSlideQrcode;
    'app-slide-split': AppSlideSplit;
    'app-slide-title': AppSlideTitle;
    'app-slide-video': AppSlideVideo;
    'app-slide-youtube': AppSlideYoutube;
    'app-slides-concept': AppSlidesConcept;
    'app-theme-switcher': AppThemeSwitcher;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-components-charts': LocalJSX.AppComponentsCharts & JSXBase.HTMLAttributes<HTMLAppComponentsChartsElement>;
      'app-components-color': LocalJSX.AppComponentsColor & JSXBase.HTMLAttributes<HTMLAppComponentsColorElement>;
      'app-components-gif': LocalJSX.AppComponentsGif & JSXBase.HTMLAttributes<HTMLAppComponentsGifElement>;
      'app-components-highlight-code': LocalJSX.AppComponentsHighlightCode & JSXBase.HTMLAttributes<HTMLAppComponentsHighlightCodeElement>;
      'app-components-inline-editor': LocalJSX.AppComponentsInlineEditor & JSXBase.HTMLAttributes<HTMLAppComponentsInlineEditorElement>;
      'app-components-lazy-img': LocalJSX.AppComponentsLazyImg & JSXBase.HTMLAttributes<HTMLAppComponentsLazyImgElement>;
      'app-components-qrcode': LocalJSX.AppComponentsQrcode & JSXBase.HTMLAttributes<HTMLAppComponentsQrcodeElement>;
      'app-components-social': LocalJSX.AppComponentsSocial & JSXBase.HTMLAttributes<HTMLAppComponentsSocialElement>;
      'app-components-youtube': LocalJSX.AppComponentsYoutube & JSXBase.HTMLAttributes<HTMLAppComponentsYoutubeElement>;
      'app-deck-actions': LocalJSX.AppDeckActions & JSXBase.HTMLAttributes<HTMLAppDeckActionsElement>;
      'app-deck-background': LocalJSX.AppDeckBackground & JSXBase.HTMLAttributes<HTMLAppDeckBackgroundElement>;
      'app-deck-events': LocalJSX.AppDeckEvents & JSXBase.HTMLAttributes<HTMLAppDeckEventsElement>;
      'app-deck-extra-features': LocalJSX.AppDeckExtraFeatures & JSXBase.HTMLAttributes<HTMLAppDeckExtraFeaturesElement>;
      'app-deck-navigation': LocalJSX.AppDeckNavigation & JSXBase.HTMLAttributes<HTMLAppDeckNavigationElement>;
      'app-deck-pager': LocalJSX.AppDeckPager & JSXBase.HTMLAttributes<HTMLAppDeckPagerElement>;
      'app-deck-size': LocalJSX.AppDeckSize & JSXBase.HTMLAttributes<HTMLAppDeckSizeElement>;
      'app-edit-default': LocalJSX.AppEditDefault & JSXBase.HTMLAttributes<HTMLAppEditDefaultElement>;
      'app-edit-fonts': LocalJSX.AppEditFonts & JSXBase.HTMLAttributes<HTMLAppEditFontsElement>;
      'app-edit-lazy-loading': LocalJSX.AppEditLazyLoading & JSXBase.HTMLAttributes<HTMLAppEditLazyLoadingElement>;
      'app-edit-markdown': LocalJSX.AppEditMarkdown & JSXBase.HTMLAttributes<HTMLAppEditMarkdownElement>;
      'app-edit-reveal': LocalJSX.AppEditReveal & JSXBase.HTMLAttributes<HTMLAppEditRevealElement>;
      'app-edit-rtl': LocalJSX.AppEditRtl & JSXBase.HTMLAttributes<HTMLAppEditRtlElement>;
      'app-edit-theming': LocalJSX.AppEditTheming & JSXBase.HTMLAttributes<HTMLAppEditThemingElement>;
      'app-footer': LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-installation': LocalJSX.AppInstallation & JSXBase.HTMLAttributes<HTMLAppInstallationElement>;
      'app-introduction': LocalJSX.AppIntroduction & JSXBase.HTMLAttributes<HTMLAppIntroductionElement>;
      'app-logo': LocalJSX.AppLogo & JSXBase.HTMLAttributes<HTMLAppLogoElement>;
      'app-menu-footer': LocalJSX.AppMenuFooter & JSXBase.HTMLAttributes<HTMLAppMenuFooterElement>;
      'app-misc-backstory': LocalJSX.AppMiscBackstory & JSXBase.HTMLAttributes<HTMLAppMiscBackstoryElement>;
      'app-misc-collections': LocalJSX.AppMiscCollections & JSXBase.HTMLAttributes<HTMLAppMiscCollectionsElement>;
      'app-misc-contact': LocalJSX.AppMiscContact & JSXBase.HTMLAttributes<HTMLAppMiscContactElement>;
      'app-misc-logo': LocalJSX.AppMiscLogo & JSXBase.HTMLAttributes<HTMLAppMiscLogoElement>;
      'app-misc-open-source': LocalJSX.AppMiscOpenSource & JSXBase.HTMLAttributes<HTMLAppMiscOpenSourceElement>;
      'app-navigation': LocalJSX.AppNavigation & JSXBase.HTMLAttributes<HTMLAppNavigationElement>;
      'app-navigation-modal': LocalJSX.AppNavigationModal & JSXBase.HTMLAttributes<HTMLAppNavigationModalElement>;
      'app-publishing': LocalJSX.AppPublishing & JSXBase.HTMLAttributes<HTMLAppPublishingElement>;
      'app-remote-control': LocalJSX.AppRemoteControl & JSXBase.HTMLAttributes<HTMLAppRemoteControlElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-running': LocalJSX.AppRunning & JSXBase.HTMLAttributes<HTMLAppRunningElement>;
      'app-slide-author': LocalJSX.AppSlideAuthor & JSXBase.HTMLAttributes<HTMLAppSlideAuthorElement>;
      'app-slide-big-img': LocalJSX.AppSlideBigImg & JSXBase.HTMLAttributes<HTMLAppSlideBigImgElement>;
      'app-slide-chart': LocalJSX.AppSlideChart & JSXBase.HTMLAttributes<HTMLAppSlideChartElement>;
      'app-slide-code': LocalJSX.AppSlideCode & JSXBase.HTMLAttributes<HTMLAppSlideCodeElement>;
      'app-slide-content': LocalJSX.AppSlideContent & JSXBase.HTMLAttributes<HTMLAppSlideContentElement>;
      'app-slide-countdown': LocalJSX.AppSlideCountdown & JSXBase.HTMLAttributes<HTMLAppSlideCountdownElement>;
      'app-slide-gif': LocalJSX.AppSlideGif & JSXBase.HTMLAttributes<HTMLAppSlideGifElement>;
      'app-slide-qrcode': LocalJSX.AppSlideQrcode & JSXBase.HTMLAttributes<HTMLAppSlideQrcodeElement>;
      'app-slide-split': LocalJSX.AppSlideSplit & JSXBase.HTMLAttributes<HTMLAppSlideSplitElement>;
      'app-slide-title': LocalJSX.AppSlideTitle & JSXBase.HTMLAttributes<HTMLAppSlideTitleElement>;
      'app-slide-video': LocalJSX.AppSlideVideo & JSXBase.HTMLAttributes<HTMLAppSlideVideoElement>;
      'app-slide-youtube': LocalJSX.AppSlideYoutube & JSXBase.HTMLAttributes<HTMLAppSlideYoutubeElement>;
      'app-slides-concept': LocalJSX.AppSlidesConcept & JSXBase.HTMLAttributes<HTMLAppSlidesConceptElement>;
      'app-theme-switcher': LocalJSX.AppThemeSwitcher & JSXBase.HTMLAttributes<HTMLAppThemeSwitcherElement>;
    }
  }
}


