/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppComponentsCharts {}
  interface AppComponentsGif {}
  interface AppComponentsHighlightCode {}
  interface AppComponentsInlineEditor {}
  interface AppComponentsLazyImg {}
  interface AppComponentsQrcode {}
  interface AppComponentsSocial {}
  interface AppComponentsYoutube {}
  interface AppDeckActions {}
  interface AppDeckBackground {}
  interface AppDeckEvents {}
  interface AppDeckExtraFeatures {}
  interface AppDeckNavigation {}
  interface AppDeckPager {}
  interface AppDeckSize {}
  interface AppEditDefault {}
  interface AppEditFonts {}
  interface AppEditLazyLoading {}
  interface AppEditMarkdown {}
  interface AppEditRtl {}
  interface AppEditTheming {}
  interface AppFooter {
    'start': boolean;
  }
  interface AppHome {}
  interface AppInstallation {}
  interface AppIntroduction {}
  interface AppLogo {}
  interface AppMenuFooter {}
  interface AppMiscBackstory {}
  interface AppMiscCollections {}
  interface AppMiscContact {}
  interface AppMiscLogo {}
  interface AppMiscOpenSource {}
  interface AppNavigation {
    'logo': boolean;
    'menuToggle': boolean;
    'navigation': boolean;
  }
  interface AppNavigationModal {}
  interface AppPublishing {}
  interface AppRemoteControl {}
  interface AppRoot {}
  interface AppRunning {}
  interface AppSlideAuthor {}
  interface AppSlideChart {}
  interface AppSlideCode {}
  interface AppSlideContent {}
  interface AppSlideCountdown {}
  interface AppSlideGif {}
  interface AppSlideQrcode {}
  interface AppSlideSplit {}
  interface AppSlideTitle {}
  interface AppSlideYoutube {}
  interface AppSlidesConcept {}
}

declare global {


  interface HTMLAppComponentsChartsElement extends Components.AppComponentsCharts, HTMLStencilElement {}
  var HTMLAppComponentsChartsElement: {
    prototype: HTMLAppComponentsChartsElement;
    new (): HTMLAppComponentsChartsElement;
  };

  interface HTMLAppComponentsGifElement extends Components.AppComponentsGif, HTMLStencilElement {}
  var HTMLAppComponentsGifElement: {
    prototype: HTMLAppComponentsGifElement;
    new (): HTMLAppComponentsGifElement;
  };

  interface HTMLAppComponentsHighlightCodeElement extends Components.AppComponentsHighlightCode, HTMLStencilElement {}
  var HTMLAppComponentsHighlightCodeElement: {
    prototype: HTMLAppComponentsHighlightCodeElement;
    new (): HTMLAppComponentsHighlightCodeElement;
  };

  interface HTMLAppComponentsInlineEditorElement extends Components.AppComponentsInlineEditor, HTMLStencilElement {}
  var HTMLAppComponentsInlineEditorElement: {
    prototype: HTMLAppComponentsInlineEditorElement;
    new (): HTMLAppComponentsInlineEditorElement;
  };

  interface HTMLAppComponentsLazyImgElement extends Components.AppComponentsLazyImg, HTMLStencilElement {}
  var HTMLAppComponentsLazyImgElement: {
    prototype: HTMLAppComponentsLazyImgElement;
    new (): HTMLAppComponentsLazyImgElement;
  };

  interface HTMLAppComponentsQrcodeElement extends Components.AppComponentsQrcode, HTMLStencilElement {}
  var HTMLAppComponentsQrcodeElement: {
    prototype: HTMLAppComponentsQrcodeElement;
    new (): HTMLAppComponentsQrcodeElement;
  };

  interface HTMLAppComponentsSocialElement extends Components.AppComponentsSocial, HTMLStencilElement {}
  var HTMLAppComponentsSocialElement: {
    prototype: HTMLAppComponentsSocialElement;
    new (): HTMLAppComponentsSocialElement;
  };

  interface HTMLAppComponentsYoutubeElement extends Components.AppComponentsYoutube, HTMLStencilElement {}
  var HTMLAppComponentsYoutubeElement: {
    prototype: HTMLAppComponentsYoutubeElement;
    new (): HTMLAppComponentsYoutubeElement;
  };

  interface HTMLAppDeckActionsElement extends Components.AppDeckActions, HTMLStencilElement {}
  var HTMLAppDeckActionsElement: {
    prototype: HTMLAppDeckActionsElement;
    new (): HTMLAppDeckActionsElement;
  };

  interface HTMLAppDeckBackgroundElement extends Components.AppDeckBackground, HTMLStencilElement {}
  var HTMLAppDeckBackgroundElement: {
    prototype: HTMLAppDeckBackgroundElement;
    new (): HTMLAppDeckBackgroundElement;
  };

  interface HTMLAppDeckEventsElement extends Components.AppDeckEvents, HTMLStencilElement {}
  var HTMLAppDeckEventsElement: {
    prototype: HTMLAppDeckEventsElement;
    new (): HTMLAppDeckEventsElement;
  };

  interface HTMLAppDeckExtraFeaturesElement extends Components.AppDeckExtraFeatures, HTMLStencilElement {}
  var HTMLAppDeckExtraFeaturesElement: {
    prototype: HTMLAppDeckExtraFeaturesElement;
    new (): HTMLAppDeckExtraFeaturesElement;
  };

  interface HTMLAppDeckNavigationElement extends Components.AppDeckNavigation, HTMLStencilElement {}
  var HTMLAppDeckNavigationElement: {
    prototype: HTMLAppDeckNavigationElement;
    new (): HTMLAppDeckNavigationElement;
  };

  interface HTMLAppDeckPagerElement extends Components.AppDeckPager, HTMLStencilElement {}
  var HTMLAppDeckPagerElement: {
    prototype: HTMLAppDeckPagerElement;
    new (): HTMLAppDeckPagerElement;
  };

  interface HTMLAppDeckSizeElement extends Components.AppDeckSize, HTMLStencilElement {}
  var HTMLAppDeckSizeElement: {
    prototype: HTMLAppDeckSizeElement;
    new (): HTMLAppDeckSizeElement;
  };

  interface HTMLAppEditDefaultElement extends Components.AppEditDefault, HTMLStencilElement {}
  var HTMLAppEditDefaultElement: {
    prototype: HTMLAppEditDefaultElement;
    new (): HTMLAppEditDefaultElement;
  };

  interface HTMLAppEditFontsElement extends Components.AppEditFonts, HTMLStencilElement {}
  var HTMLAppEditFontsElement: {
    prototype: HTMLAppEditFontsElement;
    new (): HTMLAppEditFontsElement;
  };

  interface HTMLAppEditLazyLoadingElement extends Components.AppEditLazyLoading, HTMLStencilElement {}
  var HTMLAppEditLazyLoadingElement: {
    prototype: HTMLAppEditLazyLoadingElement;
    new (): HTMLAppEditLazyLoadingElement;
  };

  interface HTMLAppEditMarkdownElement extends Components.AppEditMarkdown, HTMLStencilElement {}
  var HTMLAppEditMarkdownElement: {
    prototype: HTMLAppEditMarkdownElement;
    new (): HTMLAppEditMarkdownElement;
  };

  interface HTMLAppEditRtlElement extends Components.AppEditRtl, HTMLStencilElement {}
  var HTMLAppEditRtlElement: {
    prototype: HTMLAppEditRtlElement;
    new (): HTMLAppEditRtlElement;
  };

  interface HTMLAppEditThemingElement extends Components.AppEditTheming, HTMLStencilElement {}
  var HTMLAppEditThemingElement: {
    prototype: HTMLAppEditThemingElement;
    new (): HTMLAppEditThemingElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppInstallationElement extends Components.AppInstallation, HTMLStencilElement {}
  var HTMLAppInstallationElement: {
    prototype: HTMLAppInstallationElement;
    new (): HTMLAppInstallationElement;
  };

  interface HTMLAppIntroductionElement extends Components.AppIntroduction, HTMLStencilElement {}
  var HTMLAppIntroductionElement: {
    prototype: HTMLAppIntroductionElement;
    new (): HTMLAppIntroductionElement;
  };

  interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {}
  var HTMLAppLogoElement: {
    prototype: HTMLAppLogoElement;
    new (): HTMLAppLogoElement;
  };

  interface HTMLAppMenuFooterElement extends Components.AppMenuFooter, HTMLStencilElement {}
  var HTMLAppMenuFooterElement: {
    prototype: HTMLAppMenuFooterElement;
    new (): HTMLAppMenuFooterElement;
  };

  interface HTMLAppMiscBackstoryElement extends Components.AppMiscBackstory, HTMLStencilElement {}
  var HTMLAppMiscBackstoryElement: {
    prototype: HTMLAppMiscBackstoryElement;
    new (): HTMLAppMiscBackstoryElement;
  };

  interface HTMLAppMiscCollectionsElement extends Components.AppMiscCollections, HTMLStencilElement {}
  var HTMLAppMiscCollectionsElement: {
    prototype: HTMLAppMiscCollectionsElement;
    new (): HTMLAppMiscCollectionsElement;
  };

  interface HTMLAppMiscContactElement extends Components.AppMiscContact, HTMLStencilElement {}
  var HTMLAppMiscContactElement: {
    prototype: HTMLAppMiscContactElement;
    new (): HTMLAppMiscContactElement;
  };

  interface HTMLAppMiscLogoElement extends Components.AppMiscLogo, HTMLStencilElement {}
  var HTMLAppMiscLogoElement: {
    prototype: HTMLAppMiscLogoElement;
    new (): HTMLAppMiscLogoElement;
  };

  interface HTMLAppMiscOpenSourceElement extends Components.AppMiscOpenSource, HTMLStencilElement {}
  var HTMLAppMiscOpenSourceElement: {
    prototype: HTMLAppMiscOpenSourceElement;
    new (): HTMLAppMiscOpenSourceElement;
  };

  interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {}
  var HTMLAppNavigationElement: {
    prototype: HTMLAppNavigationElement;
    new (): HTMLAppNavigationElement;
  };

  interface HTMLAppNavigationModalElement extends Components.AppNavigationModal, HTMLStencilElement {}
  var HTMLAppNavigationModalElement: {
    prototype: HTMLAppNavigationModalElement;
    new (): HTMLAppNavigationModalElement;
  };

  interface HTMLAppPublishingElement extends Components.AppPublishing, HTMLStencilElement {}
  var HTMLAppPublishingElement: {
    prototype: HTMLAppPublishingElement;
    new (): HTMLAppPublishingElement;
  };

  interface HTMLAppRemoteControlElement extends Components.AppRemoteControl, HTMLStencilElement {}
  var HTMLAppRemoteControlElement: {
    prototype: HTMLAppRemoteControlElement;
    new (): HTMLAppRemoteControlElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppRunningElement extends Components.AppRunning, HTMLStencilElement {}
  var HTMLAppRunningElement: {
    prototype: HTMLAppRunningElement;
    new (): HTMLAppRunningElement;
  };

  interface HTMLAppSlideAuthorElement extends Components.AppSlideAuthor, HTMLStencilElement {}
  var HTMLAppSlideAuthorElement: {
    prototype: HTMLAppSlideAuthorElement;
    new (): HTMLAppSlideAuthorElement;
  };

  interface HTMLAppSlideChartElement extends Components.AppSlideChart, HTMLStencilElement {}
  var HTMLAppSlideChartElement: {
    prototype: HTMLAppSlideChartElement;
    new (): HTMLAppSlideChartElement;
  };

  interface HTMLAppSlideCodeElement extends Components.AppSlideCode, HTMLStencilElement {}
  var HTMLAppSlideCodeElement: {
    prototype: HTMLAppSlideCodeElement;
    new (): HTMLAppSlideCodeElement;
  };

  interface HTMLAppSlideContentElement extends Components.AppSlideContent, HTMLStencilElement {}
  var HTMLAppSlideContentElement: {
    prototype: HTMLAppSlideContentElement;
    new (): HTMLAppSlideContentElement;
  };

  interface HTMLAppSlideCountdownElement extends Components.AppSlideCountdown, HTMLStencilElement {}
  var HTMLAppSlideCountdownElement: {
    prototype: HTMLAppSlideCountdownElement;
    new (): HTMLAppSlideCountdownElement;
  };

  interface HTMLAppSlideGifElement extends Components.AppSlideGif, HTMLStencilElement {}
  var HTMLAppSlideGifElement: {
    prototype: HTMLAppSlideGifElement;
    new (): HTMLAppSlideGifElement;
  };

  interface HTMLAppSlideQrcodeElement extends Components.AppSlideQrcode, HTMLStencilElement {}
  var HTMLAppSlideQrcodeElement: {
    prototype: HTMLAppSlideQrcodeElement;
    new (): HTMLAppSlideQrcodeElement;
  };

  interface HTMLAppSlideSplitElement extends Components.AppSlideSplit, HTMLStencilElement {}
  var HTMLAppSlideSplitElement: {
    prototype: HTMLAppSlideSplitElement;
    new (): HTMLAppSlideSplitElement;
  };

  interface HTMLAppSlideTitleElement extends Components.AppSlideTitle, HTMLStencilElement {}
  var HTMLAppSlideTitleElement: {
    prototype: HTMLAppSlideTitleElement;
    new (): HTMLAppSlideTitleElement;
  };

  interface HTMLAppSlideYoutubeElement extends Components.AppSlideYoutube, HTMLStencilElement {}
  var HTMLAppSlideYoutubeElement: {
    prototype: HTMLAppSlideYoutubeElement;
    new (): HTMLAppSlideYoutubeElement;
  };

  interface HTMLAppSlidesConceptElement extends Components.AppSlidesConcept, HTMLStencilElement {}
  var HTMLAppSlidesConceptElement: {
    prototype: HTMLAppSlidesConceptElement;
    new (): HTMLAppSlidesConceptElement;
  };
  interface HTMLElementTagNameMap {
    'app-components-charts': HTMLAppComponentsChartsElement;
    'app-components-gif': HTMLAppComponentsGifElement;
    'app-components-highlight-code': HTMLAppComponentsHighlightCodeElement;
    'app-components-inline-editor': HTMLAppComponentsInlineEditorElement;
    'app-components-lazy-img': HTMLAppComponentsLazyImgElement;
    'app-components-qrcode': HTMLAppComponentsQrcodeElement;
    'app-components-social': HTMLAppComponentsSocialElement;
    'app-components-youtube': HTMLAppComponentsYoutubeElement;
    'app-deck-actions': HTMLAppDeckActionsElement;
    'app-deck-background': HTMLAppDeckBackgroundElement;
    'app-deck-events': HTMLAppDeckEventsElement;
    'app-deck-extra-features': HTMLAppDeckExtraFeaturesElement;
    'app-deck-navigation': HTMLAppDeckNavigationElement;
    'app-deck-pager': HTMLAppDeckPagerElement;
    'app-deck-size': HTMLAppDeckSizeElement;
    'app-edit-default': HTMLAppEditDefaultElement;
    'app-edit-fonts': HTMLAppEditFontsElement;
    'app-edit-lazy-loading': HTMLAppEditLazyLoadingElement;
    'app-edit-markdown': HTMLAppEditMarkdownElement;
    'app-edit-rtl': HTMLAppEditRtlElement;
    'app-edit-theming': HTMLAppEditThemingElement;
    'app-footer': HTMLAppFooterElement;
    'app-home': HTMLAppHomeElement;
    'app-installation': HTMLAppInstallationElement;
    'app-introduction': HTMLAppIntroductionElement;
    'app-logo': HTMLAppLogoElement;
    'app-menu-footer': HTMLAppMenuFooterElement;
    'app-misc-backstory': HTMLAppMiscBackstoryElement;
    'app-misc-collections': HTMLAppMiscCollectionsElement;
    'app-misc-contact': HTMLAppMiscContactElement;
    'app-misc-logo': HTMLAppMiscLogoElement;
    'app-misc-open-source': HTMLAppMiscOpenSourceElement;
    'app-navigation': HTMLAppNavigationElement;
    'app-navigation-modal': HTMLAppNavigationModalElement;
    'app-publishing': HTMLAppPublishingElement;
    'app-remote-control': HTMLAppRemoteControlElement;
    'app-root': HTMLAppRootElement;
    'app-running': HTMLAppRunningElement;
    'app-slide-author': HTMLAppSlideAuthorElement;
    'app-slide-chart': HTMLAppSlideChartElement;
    'app-slide-code': HTMLAppSlideCodeElement;
    'app-slide-content': HTMLAppSlideContentElement;
    'app-slide-countdown': HTMLAppSlideCountdownElement;
    'app-slide-gif': HTMLAppSlideGifElement;
    'app-slide-qrcode': HTMLAppSlideQrcodeElement;
    'app-slide-split': HTMLAppSlideSplitElement;
    'app-slide-title': HTMLAppSlideTitleElement;
    'app-slide-youtube': HTMLAppSlideYoutubeElement;
    'app-slides-concept': HTMLAppSlidesConceptElement;
  }
}

declare namespace LocalJSX {
  interface AppComponentsCharts extends JSXBase.HTMLAttributes<HTMLAppComponentsChartsElement> {}
  interface AppComponentsGif extends JSXBase.HTMLAttributes<HTMLAppComponentsGifElement> {}
  interface AppComponentsHighlightCode extends JSXBase.HTMLAttributes<HTMLAppComponentsHighlightCodeElement> {}
  interface AppComponentsInlineEditor extends JSXBase.HTMLAttributes<HTMLAppComponentsInlineEditorElement> {}
  interface AppComponentsLazyImg extends JSXBase.HTMLAttributes<HTMLAppComponentsLazyImgElement> {}
  interface AppComponentsQrcode extends JSXBase.HTMLAttributes<HTMLAppComponentsQrcodeElement> {}
  interface AppComponentsSocial extends JSXBase.HTMLAttributes<HTMLAppComponentsSocialElement> {}
  interface AppComponentsYoutube extends JSXBase.HTMLAttributes<HTMLAppComponentsYoutubeElement> {}
  interface AppDeckActions extends JSXBase.HTMLAttributes<HTMLAppDeckActionsElement> {}
  interface AppDeckBackground extends JSXBase.HTMLAttributes<HTMLAppDeckBackgroundElement> {}
  interface AppDeckEvents extends JSXBase.HTMLAttributes<HTMLAppDeckEventsElement> {}
  interface AppDeckExtraFeatures extends JSXBase.HTMLAttributes<HTMLAppDeckExtraFeaturesElement> {}
  interface AppDeckNavigation extends JSXBase.HTMLAttributes<HTMLAppDeckNavigationElement> {}
  interface AppDeckPager extends JSXBase.HTMLAttributes<HTMLAppDeckPagerElement> {}
  interface AppDeckSize extends JSXBase.HTMLAttributes<HTMLAppDeckSizeElement> {}
  interface AppEditDefault extends JSXBase.HTMLAttributes<HTMLAppEditDefaultElement> {}
  interface AppEditFonts extends JSXBase.HTMLAttributes<HTMLAppEditFontsElement> {}
  interface AppEditLazyLoading extends JSXBase.HTMLAttributes<HTMLAppEditLazyLoadingElement> {}
  interface AppEditMarkdown extends JSXBase.HTMLAttributes<HTMLAppEditMarkdownElement> {}
  interface AppEditRtl extends JSXBase.HTMLAttributes<HTMLAppEditRtlElement> {}
  interface AppEditTheming extends JSXBase.HTMLAttributes<HTMLAppEditThemingElement> {}
  interface AppFooter extends JSXBase.HTMLAttributes<HTMLAppFooterElement> {
    'start'?: boolean;
  }
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppInstallation extends JSXBase.HTMLAttributes<HTMLAppInstallationElement> {}
  interface AppIntroduction extends JSXBase.HTMLAttributes<HTMLAppIntroductionElement> {}
  interface AppLogo extends JSXBase.HTMLAttributes<HTMLAppLogoElement> {}
  interface AppMenuFooter extends JSXBase.HTMLAttributes<HTMLAppMenuFooterElement> {}
  interface AppMiscBackstory extends JSXBase.HTMLAttributes<HTMLAppMiscBackstoryElement> {}
  interface AppMiscCollections extends JSXBase.HTMLAttributes<HTMLAppMiscCollectionsElement> {}
  interface AppMiscContact extends JSXBase.HTMLAttributes<HTMLAppMiscContactElement> {}
  interface AppMiscLogo extends JSXBase.HTMLAttributes<HTMLAppMiscLogoElement> {}
  interface AppMiscOpenSource extends JSXBase.HTMLAttributes<HTMLAppMiscOpenSourceElement> {}
  interface AppNavigation extends JSXBase.HTMLAttributes<HTMLAppNavigationElement> {
    'logo'?: boolean;
    'menuToggle'?: boolean;
    'navigation'?: boolean;
  }
  interface AppNavigationModal extends JSXBase.HTMLAttributes<HTMLAppNavigationModalElement> {}
  interface AppPublishing extends JSXBase.HTMLAttributes<HTMLAppPublishingElement> {}
  interface AppRemoteControl extends JSXBase.HTMLAttributes<HTMLAppRemoteControlElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppRunning extends JSXBase.HTMLAttributes<HTMLAppRunningElement> {}
  interface AppSlideAuthor extends JSXBase.HTMLAttributes<HTMLAppSlideAuthorElement> {}
  interface AppSlideChart extends JSXBase.HTMLAttributes<HTMLAppSlideChartElement> {}
  interface AppSlideCode extends JSXBase.HTMLAttributes<HTMLAppSlideCodeElement> {}
  interface AppSlideContent extends JSXBase.HTMLAttributes<HTMLAppSlideContentElement> {}
  interface AppSlideCountdown extends JSXBase.HTMLAttributes<HTMLAppSlideCountdownElement> {}
  interface AppSlideGif extends JSXBase.HTMLAttributes<HTMLAppSlideGifElement> {}
  interface AppSlideQrcode extends JSXBase.HTMLAttributes<HTMLAppSlideQrcodeElement> {}
  interface AppSlideSplit extends JSXBase.HTMLAttributes<HTMLAppSlideSplitElement> {}
  interface AppSlideTitle extends JSXBase.HTMLAttributes<HTMLAppSlideTitleElement> {}
  interface AppSlideYoutube extends JSXBase.HTMLAttributes<HTMLAppSlideYoutubeElement> {}
  interface AppSlidesConcept extends JSXBase.HTMLAttributes<HTMLAppSlidesConceptElement> {}

  interface IntrinsicElements {
    'app-components-charts': AppComponentsCharts;
    'app-components-gif': AppComponentsGif;
    'app-components-highlight-code': AppComponentsHighlightCode;
    'app-components-inline-editor': AppComponentsInlineEditor;
    'app-components-lazy-img': AppComponentsLazyImg;
    'app-components-qrcode': AppComponentsQrcode;
    'app-components-social': AppComponentsSocial;
    'app-components-youtube': AppComponentsYoutube;
    'app-deck-actions': AppDeckActions;
    'app-deck-background': AppDeckBackground;
    'app-deck-events': AppDeckEvents;
    'app-deck-extra-features': AppDeckExtraFeatures;
    'app-deck-navigation': AppDeckNavigation;
    'app-deck-pager': AppDeckPager;
    'app-deck-size': AppDeckSize;
    'app-edit-default': AppEditDefault;
    'app-edit-fonts': AppEditFonts;
    'app-edit-lazy-loading': AppEditLazyLoading;
    'app-edit-markdown': AppEditMarkdown;
    'app-edit-rtl': AppEditRtl;
    'app-edit-theming': AppEditTheming;
    'app-footer': AppFooter;
    'app-home': AppHome;
    'app-installation': AppInstallation;
    'app-introduction': AppIntroduction;
    'app-logo': AppLogo;
    'app-menu-footer': AppMenuFooter;
    'app-misc-backstory': AppMiscBackstory;
    'app-misc-collections': AppMiscCollections;
    'app-misc-contact': AppMiscContact;
    'app-misc-logo': AppMiscLogo;
    'app-misc-open-source': AppMiscOpenSource;
    'app-navigation': AppNavigation;
    'app-navigation-modal': AppNavigationModal;
    'app-publishing': AppPublishing;
    'app-remote-control': AppRemoteControl;
    'app-root': AppRoot;
    'app-running': AppRunning;
    'app-slide-author': AppSlideAuthor;
    'app-slide-chart': AppSlideChart;
    'app-slide-code': AppSlideCode;
    'app-slide-content': AppSlideContent;
    'app-slide-countdown': AppSlideCountdown;
    'app-slide-gif': AppSlideGif;
    'app-slide-qrcode': AppSlideQrcode;
    'app-slide-split': AppSlideSplit;
    'app-slide-title': AppSlideTitle;
    'app-slide-youtube': AppSlideYoutube;
    'app-slides-concept': AppSlidesConcept;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


