/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoSlideQrcode {
        "afterSwipe": () => Promise<void>;
        "beforeSwipe": (_enter: boolean, _reveal: boolean) => Promise<boolean>;
        "content": string;
        "hideContent": () => Promise<void>;
        "imgAlt": string;
        "imgSrc": string;
        "lazyLoadContent": () => Promise<void>;
        "resizeContent": () => Promise<void>;
        "revealContent": () => Promise<void>;
    }
}
declare global {
    interface HTMLDeckgoSlideQrcodeElement extends Components.DeckgoSlideQrcode, HTMLStencilElement {
    }
    var HTMLDeckgoSlideQrcodeElement: {
        prototype: HTMLDeckgoSlideQrcodeElement;
        new (): HTMLDeckgoSlideQrcodeElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-slide-qrcode": HTMLDeckgoSlideQrcodeElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoSlideQrcode {
        "content"?: string;
        "imgAlt"?: string;
        "imgSrc"?: string;
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "deckgo-slide-qrcode": DeckgoSlideQrcode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-slide-qrcode": LocalJSX.DeckgoSlideQrcode & JSXBase.HTMLAttributes<HTMLDeckgoSlideQrcodeElement>;
        }
    }
}
