import {SlideAttributes} from '../../models/data/slide';
import {DeckAttributes} from '../../models/data/deck';

import {Attribute, Time} from '../../functions/slides/slides.did';

export class CanisterUtils {
  // TODO: typescript declaration not correctly generated by SDK -> https://forum.dfinity.org/t/fail-to-verify-certificate-in-development-update-calls/4078/14
  static toNullable<T>(value?: T): [] | [T] {
    return value ? [value] : [];
  }

  static toTimestamp(value: Date): Time {
    return BigInt(value.getTime());
  }

  static toNullableTimestamp(value?: Date): [] | [Time] {
    return value ? [this.toTimestamp(value)] : [];
  }

  static prepareAttributes(attributes: SlideAttributes | DeckAttributes): [Attribute[]] | [] {
    if (!attributes) {
      return [];
    }

    const keys: string[] = Object.keys(attributes);

    if (!keys || keys.length <= 0) {
      return [];
    }

    const results: Attribute[] = keys
      .filter((key: string) => attributes[key] !== null && attributes[key] !== undefined && attributes[key] !== '')
      .map((key: string) => ({
        name: key,
        value: `${attributes[key]}`
      }));

    return results?.length > 0 ? [results] : [];
  }
}
