export enum TargetElement {
  QR_CODE = 'qr_code',
  CHART = 'chart',
  SLIDE = 'slide',
  SECTION = 'section',
  CODE = 'code',
  TEXT = 'text',
  BACKGROUND = 'background',
  TRANSITION = 'transition',
  SIDES = 'sides',
  SHAPES = 'shapes',
  IMAGES = 'images',
  IMAGE = 'image',
  HEADER_FOOTER = 'header-footer',
}
