/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoHr {
    }
}
declare global {
    interface HTMLDeckgoHrElement extends Components.DeckgoHr, HTMLStencilElement {
    }
    var HTMLDeckgoHrElement: {
        prototype: HTMLDeckgoHrElement;
        new (): HTMLDeckgoHrElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-hr": HTMLDeckgoHrElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoHr {
    }
    interface IntrinsicElements {
        "deckgo-hr": DeckgoHr;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-hr": LocalJSX.DeckgoHr & JSXBase.HTMLAttributes<HTMLDeckgoHrElement>;
        }
    }
}
