/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoFirebaseSignin {
        "config": Record<string, string>;
        "signInSuccess": (credentials: {uid: string | undefined; githubAccessToken: string | undefined} | undefined) => void;
    }
}
declare global {
    interface HTMLDeckgoFirebaseSigninElement extends Components.DeckgoFirebaseSignin, HTMLStencilElement {
    }
    var HTMLDeckgoFirebaseSigninElement: {
        prototype: HTMLDeckgoFirebaseSigninElement;
        new (): HTMLDeckgoFirebaseSigninElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-firebase-signin": HTMLDeckgoFirebaseSigninElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoFirebaseSignin {
        "config"?: Record<string, string>;
        "signInSuccess"?: (credentials: {uid: string | undefined; githubAccessToken: string | undefined} | undefined) => void;
    }
    interface IntrinsicElements {
        "deckgo-firebase-signin": DeckgoFirebaseSignin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-firebase-signin": LocalJSX.DeckgoFirebaseSignin & JSXBase.HTMLAttributes<HTMLDeckgoFirebaseSigninElement>;
        }
    }
}
