/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoPager {
    }
}
declare global {
    interface HTMLDeckgoPagerElement extends Components.DeckgoPager, HTMLStencilElement {
    }
    var HTMLDeckgoPagerElement: {
        prototype: HTMLDeckgoPagerElement;
        new (): HTMLDeckgoPagerElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-pager": HTMLDeckgoPagerElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoPager {
        /**
          * Emitted when the user click on the pager
         */
        "onPagerClick"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "deckgo-pager": DeckgoPager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-pager": LocalJSX.DeckgoPager & JSXBase.HTMLAttributes<HTMLDeckgoPagerElement>;
        }
    }
}
