#!/usr/bin/env bash
# vim: filetype=sh
# TODO: rename to build-handler

set -euo pipefail

out=$(nix-build --no-out-link -A function-unsplash)

cat <<JSON
{
  "build_function_zip_path": "${out}/function.zip"
}
JSON
