/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoDemo {
        /**
          * A title for the frame, could be use for accessibility reason
         */
        "frameTitle": string;
        /**
          * In case you would like to load the frame as soon as the component is loaded
         */
        "instant": boolean;
        /**
          * Lazy load the iframe
         */
        "lazyLoadContent": () => Promise<void>;
        /**
          * The type of device frame. md for Android, ios for iPhone
         */
        "mode": string;
        /**
          * The source Url of your application or website. This will be used as src attribute of the encapsulated iframe
         */
        "src": string;
        /**
          * Refresh iframe size and reload content
         */
        "updateIFrame": () => Promise<void>;
    }
}
declare global {
    interface HTMLDeckgoDemoElement extends Components.DeckgoDemo, HTMLStencilElement {
    }
    var HTMLDeckgoDemoElement: {
        prototype: HTMLDeckgoDemoElement;
        new (): HTMLDeckgoDemoElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-demo": HTMLDeckgoDemoElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoDemo {
        /**
          * A title for the frame, could be use for accessibility reason
         */
        "frameTitle"?: string;
        /**
          * In case you would like to load the frame as soon as the component is loaded
         */
        "instant"?: boolean;
        /**
          * The type of device frame. md for Android, ios for iPhone
         */
        "mode"?: string;
        /**
          * The source Url of your application or website. This will be used as src attribute of the encapsulated iframe
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "deckgo-demo": DeckgoDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-demo": LocalJSX.DeckgoDemo & JSXBase.HTMLAttributes<HTMLDeckgoDemoElement>;
        }
    }
}
