/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DeckgoSlideAspectRatio {
    'afterSwipe': () => Promise<void>;
    'beforeSwipe': (_enter: boolean, _reveal: boolean) => Promise<boolean>;
    'editable': boolean;
    'getContainer': () => Promise<HTMLDivElement>;
    'grid': boolean;
    'hideContent': () => Promise<void>;
    'lazyLoadContent': () => Promise<void>;
    'ratio': number;
    'revealContent': () => Promise<void>;
  }
}

declare global {


  interface HTMLDeckgoSlideAspectRatioElement extends Components.DeckgoSlideAspectRatio, HTMLStencilElement {}
  var HTMLDeckgoSlideAspectRatioElement: {
    prototype: HTMLDeckgoSlideAspectRatioElement;
    new (): HTMLDeckgoSlideAspectRatioElement;
  };
  interface HTMLElementTagNameMap {
    'deckgo-slide-aspect-ratio': HTMLDeckgoSlideAspectRatioElement;
  }
}

declare namespace LocalJSX {
  interface DeckgoSlideAspectRatio {
    'editable'?: boolean;
    'grid'?: boolean;
    'onSlideDidLoad'?: (event: CustomEvent<void>) => void;
    'ratio'?: number;
  }

  interface IntrinsicElements {
    'deckgo-slide-aspect-ratio': DeckgoSlideAspectRatio;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'deckgo-slide-aspect-ratio': LocalJSX.DeckgoSlideAspectRatio & JSXBase.HTMLAttributes<HTMLDeckgoSlideAspectRatioElement>;
    }
  }
}


