/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DeckgoSlideVideo {
    'afterSwipe': () => Promise<void>;
    /**
    * play when swipping forward always show previous slide when swipping backward reset when leaving the slide only show next slide if video was played and then paused or ended
    */
    'beforeSwipe': (enter: boolean) => Promise<boolean>;
    'customActions': boolean;
    'customBackground': boolean;
    'hideContent': () => Promise<void>;
    'lazyLoadContent': () => Promise<void>;
    'revealContent': () => Promise<void>;
  }
}

declare global {


  interface HTMLDeckgoSlideVideoElement extends Components.DeckgoSlideVideo, HTMLStencilElement {}
  var HTMLDeckgoSlideVideoElement: {
    prototype: HTMLDeckgoSlideVideoElement;
    new (): HTMLDeckgoSlideVideoElement;
  };
  interface HTMLElementTagNameMap {
    'deckgo-slide-video': HTMLDeckgoSlideVideoElement;
  }
}

declare namespace LocalJSX {
  interface DeckgoSlideVideo extends JSXBase.HTMLAttributes<HTMLDeckgoSlideVideoElement> {
    'customActions'?: boolean;
    'customBackground'?: boolean;
    'onSlideDidLoad'?: (event: CustomEvent<void>) => void;
  }

  interface IntrinsicElements {
    'deckgo-slide-video': DeckgoSlideVideo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


