/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DeckdeckgoPalette, DeckdeckgoPaletteColor, } from "./utils/deckdeckgo-palette";
export namespace Components {
    interface DeckgoColor {
        "colorHex": string;
        "colorRgb": string;
        "label": boolean;
        "more": boolean;
        "moreAlt": string;
        "palette": DeckdeckgoPalette[];
    }
}
declare global {
    interface HTMLDeckgoColorElement extends Components.DeckgoColor, HTMLStencilElement {
    }
    var HTMLDeckgoColorElement: {
        prototype: HTMLDeckgoColorElement;
        new (): HTMLDeckgoColorElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-color": HTMLDeckgoColorElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoColor {
        "colorHex"?: string;
        "colorRgb"?: string;
        "label"?: boolean;
        "more"?: boolean;
        "moreAlt"?: string;
        "onColorChange"?: (event: CustomEvent<DeckdeckgoPaletteColor>) => void;
        "palette"?: DeckdeckgoPalette[];
    }
    interface IntrinsicElements {
        "deckgo-color": DeckgoColor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-color": LocalJSX.DeckgoColor & JSXBase.HTMLAttributes<HTMLDeckgoColorElement>;
        }
    }
}
