/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoReveal {
        "hide": () => Promise<void>;
        "hideAll": () => Promise<void>;
        "reveal": () => Promise<void>;
        "revealAll": () => Promise<void>;
        "revealProgress": 'start' | 'partial' | 'end';
    }
    interface DeckgoRevealList {
        "hide": () => Promise<void>;
        "hideAll": () => Promise<void>;
        "listTag": string;
        "reveal": () => Promise<void>;
        "revealAll": () => Promise<void>;
        "revealProgress": 'start' | 'partial' | 'end';
    }
}
declare global {
    interface HTMLDeckgoRevealElement extends Components.DeckgoReveal, HTMLStencilElement {
    }
    var HTMLDeckgoRevealElement: {
        prototype: HTMLDeckgoRevealElement;
        new (): HTMLDeckgoRevealElement;
    };
    interface HTMLDeckgoRevealListElement extends Components.DeckgoRevealList, HTMLStencilElement {
    }
    var HTMLDeckgoRevealListElement: {
        prototype: HTMLDeckgoRevealListElement;
        new (): HTMLDeckgoRevealListElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-reveal": HTMLDeckgoRevealElement;
        "deckgo-reveal-list": HTMLDeckgoRevealListElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoReveal {
        "revealProgress"?: 'start' | 'partial' | 'end';
    }
    interface DeckgoRevealList {
        "listTag"?: string;
        "revealProgress"?: 'start' | 'partial' | 'end';
    }
    interface IntrinsicElements {
        "deckgo-reveal": DeckgoReveal;
        "deckgo-reveal-list": DeckgoRevealList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-reveal": LocalJSX.DeckgoReveal & JSXBase.HTMLAttributes<HTMLDeckgoRevealElement>;
            "deckgo-reveal-list": LocalJSX.DeckgoRevealList & JSXBase.HTMLAttributes<HTMLDeckgoRevealListElement>;
        }
    }
}
