/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DeckDeckGoCustomLoad } from "./components/interfaces/custom-load";
export namespace Components {
    interface DeckgoLazyImg {
        "ariaLabel": string;
        "customLoader": boolean;
        "imgAlt": string;
        "imgErrorSrc": string;
        "imgHeight": number;
        "imgSizes": string;
        "imgSrc": string;
        "imgSrcSet": string;
        "imgWidth": number;
        "intrinsicsize": string;
        "lazyLoad": () => Promise<void>;
        "observerRootMargin": string;
        "observerThreshold": number | number[];
        "svgSrc": string;
    }
}
declare global {
    interface HTMLDeckgoLazyImgElement extends Components.DeckgoLazyImg, HTMLStencilElement {
    }
    var HTMLDeckgoLazyImgElement: {
        prototype: HTMLDeckgoLazyImgElement;
        new (): HTMLDeckgoLazyImgElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-lazy-img": HTMLDeckgoLazyImgElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoLazyImg {
        "ariaLabel"?: string;
        "customLoader"?: boolean;
        "imgAlt"?: string;
        "imgErrorSrc"?: string;
        "imgHeight"?: number;
        "imgSizes"?: string;
        "imgSrc"?: string;
        "imgSrcSet"?: string;
        "imgWidth"?: number;
        "intrinsicsize"?: string;
        "observerRootMargin"?: string;
        "observerThreshold"?: number | number[];
        "onCustomLoad"?: (event: CustomEvent<DeckDeckGoCustomLoad>) => void;
        "onLazyImgDidLoad"?: (event: CustomEvent<any>) => void;
        "svgSrc"?: string;
    }
    interface IntrinsicElements {
        "deckgo-lazy-img": DeckgoLazyImg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-lazy-img": LocalJSX.DeckgoLazyImg & JSXBase.HTMLAttributes<HTMLDeckgoLazyImgElement>;
        }
    }
}
