/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoYoutube {
        "allowFullscreen": boolean;
        "frameTitle": string;
        "height": number;
        "instant": boolean;
        "lazyLoadContent": () => Promise<void>;
        "pause": () => Promise<void>;
        "play": () => Promise<void>;
        "src": string;
        "updateIFrame": (width: number, height: number) => Promise<void>;
        "width": number;
    }
}
declare global {
    interface HTMLDeckgoYoutubeElement extends Components.DeckgoYoutube, HTMLStencilElement {
    }
    var HTMLDeckgoYoutubeElement: {
        prototype: HTMLDeckgoYoutubeElement;
        new (): HTMLDeckgoYoutubeElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-youtube": HTMLDeckgoYoutubeElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoYoutube {
        "allowFullscreen"?: boolean;
        "frameTitle"?: string;
        "height"?: number;
        "instant"?: boolean;
        "src"?: string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "deckgo-youtube": DeckgoYoutube;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-youtube": LocalJSX.DeckgoYoutube & JSXBase.HTMLAttributes<HTMLDeckgoYoutubeElement>;
        }
    }
}
