name: wai-lambda
version: 0.1.0.0
author: Nicolas Mattia <nicolas@nmattia.com>
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 David Dal Busco and Nicolas Mattia
license: MIT
license-file: LICENSE
category: Web
synopsis: Haskell Webapps on AWS Lambda
github: deckgo/wai-lambda
description: |

    ![wai-lambda](https://github.com/deckgo/wai-lambda/raw/master/assets/wai-lambda-small.png)

    Turn any [wai](https://www.stackage.org/package/wai) webapp ( [spock](https://www.spock.li/), [servant](https://docs.servant.dev/en/stable/), etc) into a handler for AWS [Lambda](https://aws.amazon.com/lambda/) and [API Gateway](https://aws.amazon.com/api-gateway/) requests.

    Works with any Lambda environment (nodejs, python, etc). Find out more in the [README](https://github.com/deckgo/wai-lambda#wai-lambda---haskell-webapps-on-aws-lambda).
extra-source-files:
    - README.md

library:
    source-dirs: ./src

dependencies:
    - aeson
    - base < 5
    - binary
    - bytestring
    - case-insensitive
    - directory
    - http-types
    - iproute
    - network
    - temporary
    - text
    - unliftio
    - unordered-containers
    - vault
    - wai

executable:
    name: wai-lambda-hello
    main: examples/Hello.hs
    dependencies:
        - wai-lambda

ghc-options:
    - -Wall
