/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DeckgoSlideChart {
    'afterSwipe': () => Promise<void>;
    'animation': boolean;
    'animationDuration': number;
    'area': boolean;
    'beforeSwipe': (enter: boolean, _reveal: boolean) => Promise<boolean>;
    'customActions': boolean;
    'customBackground': boolean;
    'datePattern': string;
    'draw': () => Promise<void>;
    'grid': boolean;
    'height': number;
    'hideContent': () => Promise<void>;
    'innerRadius': number;
    'lazyLoadContent': () => Promise<void>;
    'marginBottom': number;
    'marginLeft': number;
    'marginRight': number;
    'marginTop': number;
    'range': string[];
    'revealContent': () => Promise<void>;
    'separator': string;
    'smooth': boolean;
    'src': string;
    'ticks': number;
    'type': string;
    'width': number;
    'yAxisDomain': string;
  }
}

declare global {


  interface HTMLDeckgoSlideChartElement extends Components.DeckgoSlideChart, HTMLStencilElement {}
  var HTMLDeckgoSlideChartElement: {
    prototype: HTMLDeckgoSlideChartElement;
    new (): HTMLDeckgoSlideChartElement;
  };
  interface HTMLElementTagNameMap {
    'deckgo-slide-chart': HTMLDeckgoSlideChartElement;
  }
}

declare namespace LocalJSX {
  interface DeckgoSlideChart extends JSXBase.HTMLAttributes<HTMLDeckgoSlideChartElement> {
    'animation'?: boolean;
    'animationDuration'?: number;
    'area'?: boolean;
    'customActions'?: boolean;
    'customBackground'?: boolean;
    'datePattern'?: string;
    'grid'?: boolean;
    'height'?: number;
    'innerRadius'?: number;
    'marginBottom'?: number;
    'marginLeft'?: number;
    'marginRight'?: number;
    'marginTop'?: number;
    'onSlideDidLoad'?: (event: CustomEvent<void>) => void;
    'range'?: string[];
    'separator'?: string;
    'smooth'?: boolean;
    'src'?: string;
    'ticks'?: number;
    'type'?: string;
    'width'?: number;
    'yAxisDomain'?: string;
  }

  interface IntrinsicElements {
    'deckgo-slide-chart': DeckgoSlideChart;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


