/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoFlashlight {
        /**
          * Decrease RGB blue color with life span
         */
        "animateB": boolean;
        /**
          * Decrease RGB green color with life span
         */
        "animateG": boolean;
        /**
          * Decrease RGB red color with life span
         */
        "animateR": boolean;
        /**
          * The RGB blue color (which will fade with time)
         */
        "b": number;
        /**
          * The RGB green color (which will fade with time)
         */
        "g": number;
        /**
          * The RGB red color
         */
        "r": number;
    }
}
declare global {
    interface HTMLDeckgoFlashlightElement extends Components.DeckgoFlashlight, HTMLStencilElement {
    }
    var HTMLDeckgoFlashlightElement: {
        prototype: HTMLDeckgoFlashlightElement;
        new (): HTMLDeckgoFlashlightElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-flashlight": HTMLDeckgoFlashlightElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoFlashlight {
        /**
          * Decrease RGB blue color with life span
         */
        "animateB"?: boolean;
        /**
          * Decrease RGB green color with life span
         */
        "animateG"?: boolean;
        /**
          * Decrease RGB red color with life span
         */
        "animateR"?: boolean;
        /**
          * The RGB blue color (which will fade with time)
         */
        "b"?: number;
        /**
          * The RGB green color (which will fade with time)
         */
        "g"?: number;
        /**
          * The RGB red color
         */
        "r"?: number;
    }
    interface IntrinsicElements {
        "deckgo-flashlight": DeckgoFlashlight;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-flashlight": LocalJSX.DeckgoFlashlight & JSXBase.HTMLAttributes<HTMLDeckgoFlashlightElement>;
        }
    }
}
