/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DeckdeckgoPlaygroundTheme } from "./declarations/deckdeckgo-playground-theme";
export namespace Components {
    interface DeckgoPlayground {
        "allowFullscreen": boolean;
        "frameTitle": string;
        "height": number;
        "instant": boolean;
        "lazyLoadContent": () => Promise<void>;
        "src": string;
        "theme": DeckdeckgoPlaygroundTheme;
        "width": number;
    }
    interface DeckgoSlidePlayground {
        "afterSwipe": () => Promise<void>;
        "allowFullscreen": boolean;
        "beforeSwipe": (_enter: boolean, _reveal: boolean) => Promise<boolean>;
        "customActions": boolean;
        "customBackground": boolean;
        "height": number;
        "hideContent": () => Promise<void>;
        "lazyLoadContent": () => Promise<void>;
        "resizeContent": () => Promise<void>;
        "revealContent": () => Promise<void>;
        "src": string;
        "theme": DeckdeckgoPlaygroundTheme;
        "width": number;
    }
}
declare global {
    interface HTMLDeckgoPlaygroundElement extends Components.DeckgoPlayground, HTMLStencilElement {
    }
    var HTMLDeckgoPlaygroundElement: {
        prototype: HTMLDeckgoPlaygroundElement;
        new (): HTMLDeckgoPlaygroundElement;
    };
    interface HTMLDeckgoSlidePlaygroundElement extends Components.DeckgoSlidePlayground, HTMLStencilElement {
    }
    var HTMLDeckgoSlidePlaygroundElement: {
        prototype: HTMLDeckgoSlidePlaygroundElement;
        new (): HTMLDeckgoSlidePlaygroundElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-playground": HTMLDeckgoPlaygroundElement;
        "deckgo-slide-playground": HTMLDeckgoSlidePlaygroundElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoPlayground {
        "allowFullscreen"?: boolean;
        "frameTitle"?: string;
        "height"?: number;
        "instant"?: boolean;
        "src"?: string;
        "theme"?: DeckdeckgoPlaygroundTheme;
        "width"?: number;
    }
    interface DeckgoSlidePlayground {
        "allowFullscreen"?: boolean;
        "customActions"?: boolean;
        "customBackground"?: boolean;
        "height"?: number;
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
        "src"?: string;
        "theme"?: DeckdeckgoPlaygroundTheme;
        "width"?: number;
    }
    interface IntrinsicElements {
        "deckgo-playground": DeckgoPlayground;
        "deckgo-slide-playground": DeckgoSlidePlayground;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-playground": LocalJSX.DeckgoPlayground & JSXBase.HTMLAttributes<HTMLDeckgoPlaygroundElement>;
            "deckgo-slide-playground": LocalJSX.DeckgoSlidePlayground & JSXBase.HTMLAttributes<HTMLDeckgoSlidePlaygroundElement>;
        }
    }
}
