export interface DeckdeckgoHighlightCodeLanguageAlias {
  [index: string]: string;
}

export interface DeckdeckgoHighlightCodeLanguage {
  title: string;
  require?: string[];
}

export interface DeckdeckgoHighlightCodeLanguages {
  [index: string]: DeckdeckgoHighlightCodeLanguage;
}

export const deckdeckgoHighlightCodeLanguages: DeckdeckgoHighlightCodeLanguages = {
  markup: {title: 'Markup'},
  css: {title: 'CSS'},
  clike: {title: 'C-like'},
  javascript: {title: 'JavaScript'},
  abap: {title: 'ABAP'},
  abnf: {title: 'ABNF'},
  actionscript: {title: 'ActionScript'},
  ada: {title: 'Ada'},
  agda: {title: 'Agda'},
  al: {title: 'AL'},
  antlr4: {title: 'ANTLR4'},
  apacheconf: {title: 'Apache Configuration'},
  apl: {title: 'APL'},
  applescript: {title: 'AppleScript'},
  aql: {title: 'AQL'},
  arduino: {title: 'Arduino', require: ['cpp']},
  arff: {title: 'ARFF'},
  asciidoc: {title: 'AsciiDoc'},
  aspnet: {title: 'ASP.NET (C#)', require: ['markup', 'csharp']},
  asm6502: {title: '6502 Assembly'},
  autohotkey: {title: 'AutoHotkey'},
  autoit: {title: 'AutoIt'},
  bash: {title: 'Bash'},
  basic: {title: 'BASIC'},
  batch: {title: 'Batch'},
  bbcode: {title: 'BBcode'},
  birb: {title: 'Birb'},
  bison: {title: 'Bison', require: ['c']},
  bnf: {title: 'BNF'},
  brainfuck: {title: 'Brainfuck'},
  brightscript: {title: 'BrightScript'},
  bro: {title: 'Bro'},
  bsl: {title: 'BSL (1C:Enterprise)'},
  c: {title: 'C'},
  csharp: {title: 'C#'},
  cpp: {title: 'C++', require: ['c']},
  cil: {title: 'CIL'},
  clojure: {title: 'Clojure'},
  cmake: {title: 'CMake'},
  coffeescript: {title: 'CoffeeScript'},
  concurnas: {title: 'Concurnas'},
  csp: {title: 'Content-Security-Policy'},
  crystal: {title: 'Crystal', require: ['ruby']},
  'css-extras': {title: 'CSS Extras', require: ['css']},
  cypher: {title: 'Cypher'},
  d: {title: 'D'},
  dart: {title: 'Dart'},
  dax: {title: 'DAX'},
  dhall: {title: 'Dhall'},
  diff: {title: 'Diff'},
  django: {title: 'Django/Jinja2', require: ['markup-templating']},
  'dns-zone-file': {title: 'DNS zone file'},
  docker: {title: 'Docker'},
  ebnf: {title: 'EBNF'},
  editorconfig: {title: 'EditorConfig'},
  eiffel: {title: 'Eiffel'},
  ejs: {title: 'EJS', require: ['markup-templating']},
  elixir: {title: 'Elixir'},
  elm: {title: 'Elm'},
  etlua: {title: 'Embedded Lua templating', require: ['lua', 'markup-templating']},
  erb: {title: 'ERB', require: ['ruby', 'markup-templating']},
  erlang: {title: 'Erlang'},
  'excel-formula': {title: 'Excel Formula'},
  fsharp: {title: 'F#'},
  factor: {title: 'Factor'},
  'firestore-security-rules': {title: 'Firestore security rules'},
  flow: {title: 'Flow'},
  fortran: {title: 'Fortran'},
  ftl: {title: 'FreeMarker Template Language', require: ['markup-templating']},
  gml: {title: 'GameMaker Language'},
  gcode: {title: 'G-code'},
  gdscript: {title: 'GDScript'},
  gedcom: {title: 'GEDCOM'},
  gherkin: {title: 'Gherkin'},
  git: {title: 'Git'},
  glsl: {title: 'GLSL', require: ['c']},
  go: {title: 'Go'},
  graphql: {title: 'GraphQL'},
  groovy: {title: 'Groovy'},
  haml: {title: 'Haml', require: ['ruby']},
  handlebars: {title: 'Handlebars', require: ['markup-templating']},
  haskell: {title: 'Haskell'},
  haxe: {title: 'Haxe'},
  hcl: {title: 'HCL'},
  hlsl: {title: 'HLSL', require: ['c']},
  http: {title: 'HTTP'},
  hpkp: {title: 'HTTP Public-Key-Pins'},
  hsts: {title: 'HTTP Strict-Transport-Security'},
  ichigojam: {title: 'IchigoJam'},
  icon: {title: 'Icon'},
  ignore: {title: '.ignore'},
  inform7: {title: 'Inform 7'},
  ini: {title: 'Ini'},
  io: {title: 'Io'},
  j: {title: 'J'},
  java: {title: 'Java'},
  javadoc: {title: 'JavaDoc', require: ['markup', 'java', 'javadoclike']},
  javadoclike: {title: 'JavaDoc-like'},
  javastacktrace: {title: 'Java stack trace'},
  jolie: {title: 'Jolie'},
  jq: {title: 'JQ'},
  jsdoc: {title: 'JSDoc', require: ['javadoclike', 'typescript']},
  'js-extras': {title: 'JS Extras'},
  json: {title: 'JSON'},
  json5: {title: 'JSON5', require: ['json']},
  jsonp: {title: 'JSONP', require: ['json']},
  jsstacktrace: {title: 'JS stack trace'},
  'js-templates': {title: 'JS Templates'},
  julia: {title: 'Julia'},
  keyman: {title: 'Keyman'},
  kotlin: {title: 'Kotlin'},
  latex: {title: 'LaTeX'},
  latte: {title: 'Latte', require: ['markup-templating', 'php']},
  less: {title: 'Less', require: ['css']},
  lilypond: {title: 'LilyPond', require: ['scheme']},
  liquid: {title: 'Liquid'},
  lisp: {title: 'Lisp'},
  livescript: {title: 'LiveScript'},
  llvm: {title: 'LLVM IR'},
  lolcode: {title: 'LOLCODE'},
  lua: {title: 'Lua'},
  makefile: {title: 'Makefile'},
  markdown: {title: 'Markdown', require: ['markup']},
  'markup-templating': {title: 'Markup templating', require: ['markup']},
  matlab: {title: 'MATLAB'},
  mel: {title: 'MEL'},
  mizar: {title: 'Mizar'},
  mongodb: {title: 'MongoDB'},
  monkey: {title: 'Monkey'},
  moonscript: {title: 'MoonScript'},
  n1ql: {title: 'N1QL'},
  n4js: {title: 'N4JS'},
  'nand2tetris-hdl': {title: 'Nand To Tetris HDL'},
  naniscript: {title: 'Naninovel Script'},
  nasm: {title: 'NASM'},
  neon: {title: 'NEON'},
  nginx: {title: 'nginx'},
  nim: {title: 'Nim'},
  nix: {title: 'Nix'},
  nsis: {title: 'NSIS'},
  objectivec: {title: 'Objective-C', require: ['c']},
  ocaml: {title: 'OCaml'},
  opencl: {title: 'OpenCL', require: ['c']},
  oz: {title: 'Oz'},
  parigp: {title: 'PARI/GP'},
  parser: {title: 'Parser', require: ['markup']},
  pascal: {title: 'Pascal'},
  pascaligo: {title: 'Pascaligo'},
  pcaxis: {title: 'PC-Axis'},
  peoplecode: {title: 'PeopleCode'},
  perl: {title: 'Perl'},
  php: {title: 'PHP', require: ['markup-templating']},
  phpdoc: {title: 'PHPDoc', require: ['php', 'javadoclike']},
  'php-extras': {title: 'PHP Extras', require: ['php']},
  plsql: {title: 'PL/SQL', require: ['sql']},
  powerquery: {title: 'PowerQuery'},
  powershell: {title: 'PowerShell'},
  processing: {title: 'Processing'},
  prolog: {title: 'Prolog'},
  properties: {title: '.properties'},
  protobuf: {title: 'Protocol Buffers'},
  pug: {title: 'Pug', require: ['markup']},
  puppet: {title: 'Puppet'},
  pure: {title: 'Pure'},
  purebasic: {title: 'PureBasic'},
  purescript: {title: 'PureScript', require: ['haskell']},
  python: {title: 'Python'},
  q: {title: 'Q (kdb+ database)'},
  qml: {title: 'QML'},
  qore: {title: 'Qore'},
  r: {title: 'R'},
  racket: {title: 'Racket', require: ['scheme']},
  jsx: {title: 'React JSX', require: ['markup']},
  tsx: {title: 'React TSX', require: ['jsx', 'typescript']},
  reason: {title: 'Reason'},
  regex: {title: 'Regex'},
  renpy: {title: "Ren'py"},
  rest: {title: 'reST (reStructuredText)'},
  rip: {title: 'Rip'},
  roboconf: {title: 'Roboconf'},
  robotframework: {title: 'Robot Framework'},
  ruby: {title: 'Ruby'},
  rust: {title: 'Rust'},
  sas: {title: 'SAS'},
  sass: {title: 'Sass (Sass)', require: ['css']},
  scss: {title: 'Sass (Scss)', require: ['css']},
  scala: {title: 'Scala', require: ['java']},
  scheme: {title: 'Scheme'},
  'shell-session': {title: 'Shell session', require: ['bash']},
  smali: {title: 'Smali'},
  smalltalk: {title: 'Smalltalk'},
  smarty: {title: 'Smarty', require: ['markup-templating']},
  sml: {title: 'SML'},
  solidity: {title: 'Solidity (Ethereum)'},
  'solution-file': {title: 'Solution file'},
  soy: {title: 'Soy (Closure Template)', require: ['markup-templating']},
  sparql: {title: 'SPARQL', require: ['turtle']},
  'splunk-spl': {title: 'Splunk SPL'},
  sqf: {title: 'SQF: Status Quo Function (Arma 3)'},
  sql: {title: 'SQL'},
  stan: {title: 'Stan'},
  iecst: {title: 'Structured Text (IEC 61131-3)'},
  stylus: {title: 'Stylus'},
  swift: {title: 'Swift'},
  't4-templating': {title: 'T4 templating'},
  't4-cs': {title: 'T4 Text Templates (C#)', require: ['t4-templating', 'csharp']},
  't4-vb': {title: 'T4 Text Templates (VB)', require: ['t4-templating', 'vbnet']},
  tap: {title: 'TAP', require: ['yaml']},
  tcl: {title: 'Tcl'},
  tt2: {title: 'Template Toolkit 2', require: ['markup-templating']},
  textile: {title: 'Textile', require: ['markup']},
  toml: {title: 'TOML'},
  turtle: {title: 'Turtle'},
  twig: {title: 'Twig', require: ['markup']},
  typescript: {title: 'TypeScript'},
  typoscript: {title: 'TypoScript'},
  unrealscript: {title: 'UnrealScript'},
  vala: {title: 'Vala'},
  vbnet: {title: 'VB.Net', require: ['basic']},
  velocity: {title: 'Velocity', require: ['markup']},
  verilog: {title: 'Verilog'},
  vhdl: {title: 'VHDL'},
  vim: {title: 'vim'},
  'visual-basic': {title: 'Visual Basic'},
  warpscript: {title: 'WarpScript'},
  wasm: {title: 'WebAssembly'},
  wiki: {title: 'Wiki markup', require: ['markup']},
  xeora: {title: 'Xeora', require: ['markup']},
  'xml-doc': {title: 'XML doc (.net)', require: ['markup']},
  xojo: {title: 'Xojo (REALbasic)'},
  xquery: {title: 'XQuery', require: ['markup']},
  yaml: {title: 'YAML'},
  yang: {title: 'YANG'},
  zig: {title: 'Zig'},
};
