/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  DeckdeckgoHighlightCodeAnchor,
} from './components/declarations/deckdeckgo-highlight-code-anchor';


export namespace Components {

  interface DeckgoHighlightCode {
    'anchor': string;
    'anchorZoom': string;
    'findNextAnchor': (enter: boolean) => Promise<DeckdeckgoHighlightCodeAnchor>;
    'hideAnchor': boolean;
    'highlightLines': string;
    'language': string;
    'load': () => Promise<void>;
    'src': string;
    'zoomCode': (zoom: boolean) => Promise<void>;
  }
  interface DeckgoHighlightCodeAttributes extends StencilHTMLAttributes {
    'anchor'?: string;
    'anchorZoom'?: string;
    'hideAnchor'?: boolean;
    'highlightLines'?: string;
    'language'?: string;
    'onPrismLanguageLoaded'?: (event: CustomEvent<string>) => void;
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DeckgoHighlightCode': Components.DeckgoHighlightCode;
  }

  interface StencilIntrinsicElements {
    'deckgo-highlight-code': Components.DeckgoHighlightCodeAttributes;
  }


  interface HTMLDeckgoHighlightCodeElement extends Components.DeckgoHighlightCode, HTMLStencilElement {}
  var HTMLDeckgoHighlightCodeElement: {
    prototype: HTMLDeckgoHighlightCodeElement;
    new (): HTMLDeckgoHighlightCodeElement;
  };

  interface HTMLElementTagNameMap {
    'deckgo-highlight-code': HTMLDeckgoHighlightCodeElement
  }

  interface ElementTagNameMap {
    'deckgo-highlight-code': HTMLDeckgoHighlightCodeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
