/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DeckgoSlideAuthor {
    'afterSwipe': () => Promise<void>;
    'beforeSwipe': (_enter: boolean, _reveal: boolean) => Promise<boolean>;
    'customActions': boolean;
    'customBackground': boolean;
    'hideContent': () => Promise<void>;
    'imgAlt': string;
    'imgSrc': string;
    'lazyLoadContent': () => Promise<void>;
    'revealContent': () => Promise<void>;
  }
}

declare global {


  interface HTMLDeckgoSlideAuthorElement extends Components.DeckgoSlideAuthor, HTMLStencilElement {}
  var HTMLDeckgoSlideAuthorElement: {
    prototype: HTMLDeckgoSlideAuthorElement;
    new (): HTMLDeckgoSlideAuthorElement;
  };
  interface HTMLElementTagNameMap {
    'deckgo-slide-author': HTMLDeckgoSlideAuthorElement;
  }
}

declare namespace LocalJSX {
  interface DeckgoSlideAuthor {
    'customActions'?: boolean;
    'customBackground'?: boolean;
    'imgAlt'?: string;
    'imgSrc'?: string;
    'onSlideDidLoad'?: (event: CustomEvent<void>) => void;
  }

  interface IntrinsicElements {
    'deckgo-slide-author': DeckgoSlideAuthor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'deckgo-slide-author': LocalJSX.DeckgoSlideAuthor & JSXBase.HTMLAttributes<HTMLDeckgoSlideAuthorElement>;
    }
  }
}


