// TODO: Duplicate related WebComponents to reduce JS chunks. Ultimately move this to a utilities

export enum DeckdeckgoHighlightCodeCarbonTheme {
  '3024-NIGHT' = '3024-night',
  'A11Y-DARK' = 'a11y-dark',
  BLACKBOARD = 'blackboard',
  'BASE16-DARK' = 'base16-dark',
  'BASE16-LIGHT' = 'base16-light',
  COBALT = 'cobalt',
  DRACULA = 'dracula',
  DUOTONE = 'duotone',
  HOPSCOTCH = 'hopscotch',
  LUCARIO = 'lucario',
  MATERIAL = 'material',
  MONOKAI = 'monokai',
  'NIGHT-OWL' = 'night-owl',
  NORD = 'nord',
  'OCEANIC-NEXT' = 'oceanic-next',
  'ONE-LIGHT' = 'one-light',
  'ONE-DARK' = 'one-dark',
  PANDA = 'panda',
  PARAISO = 'paraiso',
  SETI = 'seti',
  'SHADES-OF-PURPLE' = 'shades-of-purple',
  'SOLARIZED-DARK' = 'solarized-dark',
  'SOLARIZED-LIGHT' = 'solarized-light',
  SYNTHWAVE = 'synthwave',
  TWILIGHT = 'twilight',
  VERMINAL = 'verminal',
  VSCODE = 'vscode',
  YETI = 'yeti',
  ZENBURN = 'zenburn'
}
