name: deckdeckgo-handler
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 David Dal Busco and Nicolas Mattia
license: AGPL-3

dependencies:
    - aeson
    - amazonka
    - amazonka-dynamodb
    - base
    - bytestring
    - directory
    - hasql
    - filepath
    - firebase-login
    - http-client
    - http-types
    - lens
    - mtl
    - contravariant
    - random
    - servant
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - swagger2
    - text
    - unliftio
    - unordered-containers
    - wai
    - wai-cors
    - wai-lambda

ghc-options:
    - -Wall

library:
    source-dirs: src

executables:

    # The AWS Lambda handler
    handler:
        main: app/Handler.hs
        dependencies:
            - deckdeckgo-handler

    # The API
    swagger:
        main: app/Swagger.hs
        dependencies:
            - warp
            - deckdeckgo-handler
            - servant-swagger
            - servant-swagger-ui

    test:
        main: app/Test.hs
        dependencies:
            - deckdeckgo-handler
            - http-client
            - http-client-tls
            - lens
            - port-utils
            - servant-client
            - tasty
            - tasty-hunit
            - warp
