/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoWordCloud {
        "font": string;
        "height": number;
        "width": number;
    }
}
declare global {
    interface HTMLDeckgoWordCloudElement extends Components.DeckgoWordCloud, HTMLStencilElement {
    }
    var HTMLDeckgoWordCloudElement: {
        prototype: HTMLDeckgoWordCloudElement;
        new (): HTMLDeckgoWordCloudElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-word-cloud": HTMLDeckgoWordCloudElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoWordCloud {
        "font"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "deckgo-word-cloud": DeckgoWordCloud;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-word-cloud": LocalJSX.DeckgoWordCloud & JSXBase.HTMLAttributes<HTMLDeckgoWordCloudElement>;
        }
    }
}
