/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoWordCloud {
        /**
          * To set the component has being editable (contenteditable will be applied on the slot on click)
         */
        "editable": boolean;
        /**
          * Call the load and resize of the word cloud
         */
        "lazyLoadContent": () => Promise<void>;
        /**
          * Margin bottom in pixels
         */
        "marginBottom": number;
        /**
          * Margin left in pixels
         */
        "marginLeft": number;
        /**
          * Margin right in pixels
         */
        "marginRight": number;
        /**
          * Margin top in pixels
         */
        "marginTop": number;
    }
}
declare global {
    interface HTMLDeckgoWordCloudElement extends Components.DeckgoWordCloud, HTMLStencilElement {
    }
    var HTMLDeckgoWordCloudElement: {
        prototype: HTMLDeckgoWordCloudElement;
        new (): HTMLDeckgoWordCloudElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-word-cloud": HTMLDeckgoWordCloudElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoWordCloud {
        /**
          * To set the component has being editable (contenteditable will be applied on the slot on click)
         */
        "editable"?: boolean;
        /**
          * Margin bottom in pixels
         */
        "marginBottom"?: number;
        /**
          * Margin left in pixels
         */
        "marginLeft"?: number;
        /**
          * Margin right in pixels
         */
        "marginRight"?: number;
        /**
          * Margin top in pixels
         */
        "marginTop"?: number;
        /**
          * Emit the host element when modified
          * @private
         */
        "onWordCloudDidChange"?: (event: CustomEvent<HTMLElement>) => void;
    }
    interface IntrinsicElements {
        "deckgo-word-cloud": DeckgoWordCloud;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-word-cloud": LocalJSX.DeckgoWordCloud & JSXBase.HTMLAttributes<HTMLDeckgoWordCloudElement>;
        }
    }
}
