/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoSocial {
        /**
          * Your Dev username. It will be concatenated automatically with https://dev.to/
         */
        "dev": string;
        /**
          * In case you would like to provide the URI of your choice
         */
        "fullUrl": string;
        /**
          * Your Github username. It will be concatenated automatically with https://github.com/
         */
        "github": string;
        "lazyLoadContent": () => Promise<void>;
        /**
          * Your Linkedin username. It will be concatenated automatically with https://www.linkedin.com/in/
         */
        "linkedin": string;
        /**
          * Your Medium username. username will be replaced automatically from https://username.medium.com/
         */
        "medium": string;
        /**
          * Your Twitter username. It will be concatenated automatically with https://twitter.com/
         */
        "twitter": string;
    }
}
declare global {
    interface HTMLDeckgoSocialElement extends Components.DeckgoSocial, HTMLStencilElement {
    }
    var HTMLDeckgoSocialElement: {
        prototype: HTMLDeckgoSocialElement;
        new (): HTMLDeckgoSocialElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-social": HTMLDeckgoSocialElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoSocial {
        /**
          * Your Dev username. It will be concatenated automatically with https://dev.to/
         */
        "dev"?: string;
        /**
          * In case you would like to provide the URI of your choice
         */
        "fullUrl"?: string;
        /**
          * Your Github username. It will be concatenated automatically with https://github.com/
         */
        "github"?: string;
        /**
          * Your Linkedin username. It will be concatenated automatically with https://www.linkedin.com/in/
         */
        "linkedin"?: string;
        /**
          * Your Medium username. username will be replaced automatically from https://username.medium.com/
         */
        "medium"?: string;
        /**
          * Your Twitter username. It will be concatenated automatically with https://twitter.com/
         */
        "twitter"?: string;
    }
    interface IntrinsicElements {
        "deckgo-social": DeckgoSocial;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-social": LocalJSX.DeckgoSocial & JSXBase.HTMLAttributes<HTMLDeckgoSocialElement>;
        }
    }
}
