import {decks as deckIc} from '../../../functions/decks/index';

import authStore from '../../../stores/auth.store';
import syncStore from '../../../stores/sync.store';

import {SyncData, SyncDataDeck} from '../../../types/editor/sync';

import {internetComputer} from '../../../utils/core/environment.utils';

import {SyncService} from './sync.service';

// TODO: can we move this in a web worker? the IC SDK is compatible?

export class SyncIcService extends SyncService {
  // @Override
  async upload(syncData: SyncData | undefined) {
    if (!syncData) {
      return;
    }

    if (!authStore.state.loggedIn || !navigator.onLine) {
      return;
    }

    if (!internetComputer()) {
      return;
    }

    syncStore.state.sync = 'in_progress';

    await this.uploadDecksIC(syncData);

    await this.clean(syncData);
  }

  private async clean({syncedAt}: SyncData) {
    await this.cleanPending(syncedAt);

    await this.updateSyncState();
  }

  private async uploadDecksIC({updateDecks}: SyncData) {
    if (!updateDecks || updateDecks.length <= 0) {
      return;
    }

    const promises: Promise<void>[] = updateDecks.map((deck: SyncDataDeck) => this.uploadDeckIC(deck));
    await Promise.all(promises);
  }

  private async uploadDeckIC({deck}: SyncDataDeck) {
    if (!deck) {
      return;
    }

    // TODO: following can take ages

    // TODO: Locally error -> Fail to verify certificate - https://forum.dfinity.org/t/fail-to-verify-certificate-in-development-update-calls/4078/14

    await deckIc.set({
      id: deck.id,
      data: {
        name: deck.data.name,
        header: this.toNullString(deck.data.header)
      }
    });

    // TODO: remove, just for test
    console.log('Deck IC Get:', await deckIc.get(deck.id));
  }

  // TODO: typescript declaration not correctly generated by SDK -> https://forum.dfinity.org/t/fail-to-verify-certificate-in-development-update-calls/4078/14
  private toNullString(value?: string): [] | [string] {
    return value ? [value] : [];
  }
}
