/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoIcSignin {
        "config": Record<string, string>;
        "i18n": Record<string, Record<string, string>>;
        "signInError": (err?: string) => void;
        "signInSuccess": () => void;
    }
}
declare global {
    interface HTMLDeckgoIcSigninElement extends Components.DeckgoIcSignin, HTMLStencilElement {
    }
    var HTMLDeckgoIcSigninElement: {
        prototype: HTMLDeckgoIcSigninElement;
        new (): HTMLDeckgoIcSigninElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-ic-signin": HTMLDeckgoIcSigninElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoIcSignin {
        "config"?: Record<string, string>;
        "i18n"?: Record<string, Record<string, string>>;
        "onDdgSignInError"?: (event: CustomEvent<string | undefined>) => void;
        "onDdgSignInSuccess"?: (event: CustomEvent<void>) => void;
        "onInProgress"?: (event: CustomEvent<boolean>) => void;
        "signInError"?: (err?: string) => void;
        "signInSuccess"?: () => void;
    }
    interface IntrinsicElements {
        "deckgo-ic-signin": DeckgoIcSignin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-ic-signin": LocalJSX.DeckgoIcSignin & JSXBase.HTMLAttributes<HTMLDeckgoIcSigninElement>;
        }
    }
}
