/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoStudio {
    }
}
declare global {
    interface HTMLDeckgoStudioElement extends Components.DeckgoStudio, HTMLStencilElement {
    }
    var HTMLDeckgoStudioElement: {
        prototype: HTMLDeckgoStudioElement;
        new (): HTMLDeckgoStudioElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-studio": HTMLDeckgoStudioElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoStudio {
    }
    interface IntrinsicElements {
        "deckgo-studio": DeckgoStudio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-studio": LocalJSX.DeckgoStudio & JSXBase.HTMLAttributes<HTMLDeckgoStudioElement>;
        }
    }
}
