/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StyloConfig } from "@papyrs/stylo";
import { Doc } from "@deckdeckgo/editor";
export namespace Components {
    interface DeckgoDocIndicator {
        "busy": boolean;
    }
    interface DeckgoStudioDoc {
        "init": () => Promise<void>;
        "loadDoc": (docId: string | undefined) => Promise<Doc> | undefined;
        "resetDoc": () => void | undefined;
        "styloConfig": Partial<StyloConfig>;
    }
}
declare global {
    interface HTMLDeckgoDocIndicatorElement extends Components.DeckgoDocIndicator, HTMLStencilElement {
    }
    var HTMLDeckgoDocIndicatorElement: {
        prototype: HTMLDeckgoDocIndicatorElement;
        new (): HTMLDeckgoDocIndicatorElement;
    };
    interface HTMLDeckgoStudioDocElement extends Components.DeckgoStudioDoc, HTMLStencilElement {
    }
    var HTMLDeckgoStudioDocElement: {
        prototype: HTMLDeckgoStudioDocElement;
        new (): HTMLDeckgoStudioDocElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-doc-indicator": HTMLDeckgoDocIndicatorElement;
        "deckgo-studio-doc": HTMLDeckgoStudioDocElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoDocIndicator {
        "busy"?: boolean;
    }
    interface DeckgoStudioDoc {
        "loadDoc"?: (docId: string | undefined) => Promise<Doc> | undefined;
        "onDocDataEvents"?: (event: CustomEvent<'init' | 'destroy'>) => void;
        "onDocDidLoad"?: (event: CustomEvent<HTMLElement>) => void;
        "onDocReady"?: (event: CustomEvent<boolean>) => void;
        "resetDoc"?: () => void | undefined;
        "styloConfig"?: Partial<StyloConfig>;
    }
    interface IntrinsicElements {
        "deckgo-doc-indicator": DeckgoDocIndicator;
        "deckgo-studio-doc": DeckgoStudioDoc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-doc-indicator": LocalJSX.DeckgoDocIndicator & JSXBase.HTMLAttributes<HTMLDeckgoDocIndicatorElement>;
            "deckgo-studio-doc": LocalJSX.DeckgoStudioDoc & JSXBase.HTMLAttributes<HTMLDeckgoStudioDocElement>;
        }
    }
}
