/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoSocialImg {
        /**
          * The social image width
          * @default 1200px
         */
        "height": string;
        /**
          * An optional image (https://....) that can for example be displayed as logo.
         */
        "imgSrc": string;
        /**
          * A padding to create space around the text and the content
          * @default 32
         */
        "innerPadding": number;
        /**
          * A padding to create space around the content
          * @default 64
         */
        "padding": number;
        /**
          * The color for rectangles
          * @default #3dc2ff
         */
        "rectColor": string;
        /**
          * The width of the stroke of the rectangles
          * @default 4
         */
        "rectStrokeWidth": number;
        /**
          * The text to display (per default clamped with three dots "..." after some lines, see CSS)
         */
        "text": string;
        /**
          * Transform the rendered svg to an image
          * @param type The type of output (default 'image/webp')
          * @returns The image as blob
         */
        "toBlob": (type?: string) => Promise<Blob>;
        /**
          * The social image width
          * @default 1200px
         */
        "width": string;
    }
}
declare global {
    interface HTMLDeckgoSocialImgElement extends Components.DeckgoSocialImg, HTMLStencilElement {
    }
    var HTMLDeckgoSocialImgElement: {
        prototype: HTMLDeckgoSocialImgElement;
        new (): HTMLDeckgoSocialImgElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-social-img": HTMLDeckgoSocialImgElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoSocialImg {
        /**
          * The social image width
          * @default 1200px
         */
        "height"?: string;
        /**
          * An optional image (https://....) that can for example be displayed as logo.
         */
        "imgSrc"?: string;
        /**
          * A padding to create space around the text and the content
          * @default 32
         */
        "innerPadding"?: number;
        /**
          * A padding to create space around the content
          * @default 64
         */
        "padding"?: number;
        /**
          * The color for rectangles
          * @default #3dc2ff
         */
        "rectColor"?: string;
        /**
          * The width of the stroke of the rectangles
          * @default 4
         */
        "rectStrokeWidth"?: number;
        /**
          * The text to display (per default clamped with three dots "..." after some lines, see CSS)
         */
        "text"?: string;
        /**
          * The social image width
          * @default 1200px
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "deckgo-social-img": DeckgoSocialImg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-social-img": LocalJSX.DeckgoSocialImg & JSXBase.HTMLAttributes<HTMLDeckgoSocialImgElement>;
        }
    }
}
