/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoSlideAspectRatio {
        "afterSwipe": () => Promise<void>;
        "beforeSwipe": (_enter: boolean, _reveal: boolean) => Promise<boolean>;
        /**
          * If you provide actions for the all deck but, a specific one for this slide, set this option to true
         */
        "customActions": boolean;
        /**
          * If you define a background for the all deck but, a specific one for this slide, set this option to true
         */
        "customBackground": boolean;
        /**
          * Per default point-events are set to none for this template making it read-only respectively not editable
         */
        "editable": boolean;
        "getContainer": () => Promise<HTMLDivElement>;
        /**
          * Display a grid behind the content. Note that the grid would only be display if not fullscreen
         */
        "grid": boolean;
        "hideContent": () => Promise<void>;
        "lazyLoadContent": () => Promise<void>;
        /**
          * The aspect ratio of the displayed content. Per default 16 being the width and 9 the height
         */
        "ratio": number;
        "revealContent": () => Promise<void>;
    }
}
declare global {
    interface HTMLDeckgoSlideAspectRatioElement extends Components.DeckgoSlideAspectRatio, HTMLStencilElement {
    }
    var HTMLDeckgoSlideAspectRatioElement: {
        prototype: HTMLDeckgoSlideAspectRatioElement;
        new (): HTMLDeckgoSlideAspectRatioElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-slide-aspect-ratio": HTMLDeckgoSlideAspectRatioElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoSlideAspectRatio {
        /**
          * If you provide actions for the all deck but, a specific one for this slide, set this option to true
         */
        "customActions"?: boolean;
        /**
          * If you define a background for the all deck but, a specific one for this slide, set this option to true
         */
        "customBackground"?: boolean;
        /**
          * Per default point-events are set to none for this template making it read-only respectively not editable
         */
        "editable"?: boolean;
        /**
          * Display a grid behind the content. Note that the grid would only be display if not fullscreen
         */
        "grid"?: boolean;
        /**
          * Triggered when the slide is loaded
         */
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
        /**
          * The aspect ratio of the displayed content. Per default 16 being the width and 9 the height
         */
        "ratio"?: number;
    }
    interface IntrinsicElements {
        "deckgo-slide-aspect-ratio": DeckgoSlideAspectRatio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-slide-aspect-ratio": LocalJSX.DeckgoSlideAspectRatio & JSXBase.HTMLAttributes<HTMLDeckgoSlideAspectRatioElement>;
        }
    }
}
