name: CI - Site

on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * 4'

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./site
      - name: Build
        run: npm run build
        working-directory: ./site
        env:
          FIREBASE_FEED_TOKEN: ${{ secrets.FIREBASE_FEED_TOKEN }}
          FIREBASE_FUNCTIONS_URL: ${{ secrets.FIREBASE_FUNCTIONS_URL }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'default'
          PROJECT_PATH: './site'
